import type {ContentLanguage} from './localization.js';

export const ERROR_TEXT = {
  PROVIDER_BLOB_ID_INVALID: {en: "The file storage identifier is invalid. Refresh and select the file again.", 'zh-CN': "文件存储标识无效，请刷新后重新选择文件。"},
  PROVIDER_INPUT_INVALID: {en: "The file size or checksum is invalid. Select the file and upload again.", 'zh-CN': "文件大小或校验信息无效，请重新选择并上传文件。"},
  SERVER_VOLUME_PATH_INVALID: {en: "The server storage directory is unsafe or unavailable. Ask an administrator to check it.", 'zh-CN': "服务器存储目录不安全或不可用，请联系管理员检查。"},
  PROVIDER_SIZE_MISMATCH: {en: "The received file size does not match. Upload the file again.", 'zh-CN': "接收到的文件大小不一致，请重新上传。"},
  PROVIDER_INTEGRITY_MISMATCH: {en: "File verification failed. Upload or sync the file again.", 'zh-CN': "文件校验失败，请重新上传或同步。"},
  SERVER_VOLUME_WRITE_FAILED: {en: "The server could not save the file. Ask an administrator to check disk space and directory permissions.", 'zh-CN': "服务器无法保存文件，请联系管理员检查磁盘空间和目录权限。"},
  SERVER_VOLUME_READ_FAILED: {en: "The server could not read the file. Ask an administrator to check the storage volume.", 'zh-CN': "服务器无法读取文件，请联系管理员检查存储卷。"},
  SERVER_VOLUME_DELETE_FAILED: {en: "The server could not remove stored file content. Ask an administrator to check storage permissions.", 'zh-CN': "服务器无法清理文件内容，请联系管理员检查存储权限。"},
  S3_INPUT_INVALID: {en: "The S3 file metadata is invalid. Select the file and upload again.", 'zh-CN': "S3 文件信息无效，请重新选择并上传文件。"},
  S3_WRITE_FAILED: {en: "S3 could not save the file. Check the connection, credentials, and bucket write permission.", 'zh-CN': "S3 无法保存文件，请检查连接、凭据及存储桶写入权限。"},
  S3_INTEGRITY_MISMATCH: {en: "The S3 file failed verification. Upload the file again.", 'zh-CN': "S3 文件校验失败，请重新上传。"},
  S3_READ_FAILED: {en: "The S3 file could not be read. Check the connection, credentials, and bucket read permission.", 'zh-CN': "无法读取 S3 文件，请检查连接、凭据及存储桶读取权限。"},
  S3_DELETE_FAILED: {en: "The S3 file could not be removed. Check the connection and bucket delete permission.", 'zh-CN': "无法清理 S3 文件，请检查连接及存储桶删除权限。"},
  STAGING_PATH_INVALID: {en: "The upload staging directory is unsafe or unavailable. Ask an administrator to check it.", 'zh-CN': "上传暂存目录不安全或不可用，请联系管理员检查。"},
  UPLOAD_TOO_LARGE: {en: "The file exceeds the upload limit. Choose a smaller file.", 'zh-CN': "文件超过上传大小限制，请选择较小的文件。"},
  UPLOAD_SIZE_MISMATCH: {en: "The uploaded file size does not match. Select the file and upload again.", 'zh-CN': "上传的文件大小不一致，请重新选择并上传文件。"},
  STAGING_WRITE_FAILED: {en: "The server could not stage the upload. Ask an administrator to check free disk space and directory permissions.", 'zh-CN': "服务器无法暂存上传文件，请联系管理员检查磁盘空间和目录权限。"},
  UPLOAD_INTERRUPTED: {en: "The upload was interrupted. Check the connection and upload again.", 'zh-CN': "上传中断，请检查网络后重新上传。"},
  UPLOAD_HASH_MISMATCH: {en: "The uploaded file failed verification. Select the file and upload again.", 'zh-CN': "上传文件校验失败，请重新选择并上传文件。"},
  STAGING_CLEANUP_FAILED: {en: "Temporary upload files could not be removed. Ask an administrator to check directory permissions.", 'zh-CN': "无法清理临时上传文件，请联系管理员检查目录权限。"},
  REQUIRED_TEXT: {en: "Enter non-empty text, up to {max} characters.", 'zh-CN': "请输入非空文本，最多 {max} 个字符。"},
  INVALID_TEXT: {en: "Enter text of no more than {max} characters.", 'zh-CN': "请输入文本，最多 {max} 个字符。"},
  INVALID_INTEGER: {en: "Enter a whole number.", 'zh-CN': "请输入整数。"},
  POSITIVE_INTEGER_REQUIRED: {en: "Enter a positive whole number.", 'zh-CN': "请输入大于零的整数。"},
  NON_NEGATIVE_INTEGER_REQUIRED: {en: "Enter a non-negative whole number.", 'zh-CN': "请输入非负整数。"},
  NUMBER_OUT_OF_RANGE: {en: "Enter a whole number between 0 and {max}.", 'zh-CN': "请输入 0 到 {max} 之间的整数。"},
  CLIENT_REQUEST_INVALID: {en: "The request format is incompatible with the server. Reload the page or update the Chair Agent.", 'zh-CN': "请求格式与服务器不兼容，请刷新页面或更新主席 Agent。"},
  INVALID_CHECKSUM: {en: "File verification information is invalid. Select and upload the file again.", 'zh-CN': "文件校验信息无效，请重新选择并上传文件。"},
  INVALID_STORAGE_KEY: {en: "The file storage path is invalid. Ask an administrator to check the storage configuration.", 'zh-CN': "文件存储路径无效，请联系管理员检查存储配置。"},
  INHERITED_SPEECH_CANNOT_YIELD: {en: "Inherited speaking time cannot be yielded again.", 'zh-CN': "继承的发言时间不能再次让渡。"},
  PAUSE_BEFORE_YIELD: {en: "Pause the speech with more than one second remaining before yielding.", 'zh-CN': "请在剩余时间超过一秒时暂停发言，再进行让渡。"},
  STORAGE_CACHE_CAPACITY_UNAVAILABLE: {en: "Download cache space is unavailable. Ask an administrator to check cache capacity and free disk space.", 'zh-CN': "下载缓存空间不可用，请联系管理员检查缓存容量和磁盘剩余空间。"},
  STORAGE_AGENT_OFFLINE: {en: "The Chair computer is offline. Bring it online before downloading this file.", 'zh-CN': "主席电脑已离线，请让该电脑上线后再下载此文件。"},
  STORAGE_AGENT_UPGRADE_REQUIRED: {en: "Update the Chair Agent to support file downloads through the server.", 'zh-CN': "请升级主席 Agent，以支持通过服务器下载文件。"},
  STORAGE_AGENT_SOURCE_MISSING: {en: "The source file is missing or failed verification on the Chair computer. Check the file and sync again.", 'zh-CN': "主席电脑上的源文件缺失或校验失败，请检查文件并重新同步。"},
  INVALID_OBJECT: {en: "The settings must be an object. Reload the page or check the imported file format.", 'zh-CN': "设置格式必须是对象，请刷新页面或检查导入文件格式。"},
  INVALID_LANGUAGE_TAG: {en: "Use a valid language code, such as zh-CN or en.", 'zh-CN': "请使用有效的语言代码，例如 zh-CN 或 en。"},
  INVALID_WEBP_FLAG: {en: "Choose a valid WebP flag image.", 'zh-CN': "请选择有效的 WebP 格式旗帜图片。"},
  INVALID_STANDARD_FLAG: {en: "Choose a standard flag with a two-letter country code.", 'zh-CN': "请选择使用两位字母国家代码的标准旗帜。"},
  FLAG_EMOJI_TOO_LONG: {en: "The flag emoji must fit within 32 UTF-8 bytes. Choose a shorter emoji.", 'zh-CN': "旗帜表情不能超过 32 个 UTF-8 字节，请选择较短的表情。"},
  FLAG_IMAGE_TOO_LARGE: {en: "The processed flag image must be a valid WebP image no larger than 256 KB.", 'zh-CN': "处理后的旗帜必须是有效的 WebP 图片，且不超过 256 KB。"},
  FLAG_DIMENSIONS_INVALID: {en: "Flag images must be at most 256 × 160 pixels.", 'zh-CN': "旗帜图片尺寸不能超过 256 × 160 像素。"},
  INVALID_FLAG_TYPE: {en: "Choose a standard flag, emoji, or image.", 'zh-CN': "请选择标准旗帜、表情或图片。"},
  INVALID_COUNTRY_LANGUAGES: {en: "Declare 1–32 unique country languages, including the default language.", 'zh-CN': "请设置 1–32 种不重复的国家语言，并包含默认语言。"},
  TOO_MANY_COUNTRIES: {en: "A country template can contain at most 512 countries.", 'zh-CN': "国家模板最多包含 512 个国家。"},
  INVALID_STABLE_KEY: {en: "Identifiers must be unique, start with a letter or digit, and contain up to 128 letters, digits, dots, underscores, colons, or hyphens.", 'zh-CN': "标识必须唯一，以字母或数字开头，最多 128 个字符，只能使用字母、数字、点、下划线、冒号和连字符。"},
  UNDECLARED_COUNTRY_LANGUAGE: {en: "Country names must use languages declared in the template.", 'zh-CN': "国家名称必须使用模板中已声明的语言。"},
  INVALID_TEMPLATE_MEMBER_COUNT: {en: "A committee template must contain 1–512 members.", 'zh-CN': "委员会模板必须包含 1–512 个成员。"},
  VOTING_RIGHTS_REQUIRED: {en: "Enable voting rights before enabling veto power or required voting.", 'zh-CN': "请先启用表决权，再启用否决权或不得弃权。"},
  INVALID_REJECTION_COUNT: {en: "Set between 1 and 30 rejection types.", 'zh-CN': "请设置 1–30 种驳回类型。"},
  INVALID_REJECTION_TRANSLATIONS: {en: "Use Chinese or English rejection text, up to {max} characters.", 'zh-CN': "请填写中文或英文驳回文本，最多 {max} 个字符。"},
  REJECTION_TEXT_REQUIRED: {en: "Enter a rejection label and message.", 'zh-CN': "请填写驳回类型名称和提示内容。"},
  DUPLICATE_REJECTION_TYPE: {en: "Rejection identifiers and labels must be unique.", 'zh-CN': "驳回类型的标识和名称不能重复。"},
  FILE_EXTENSIONS_REQUIRED: {en: "Set the allowed extensions for each file type.", 'zh-CN': "请为每种文件类型设置允许的后缀名。"},
  INVALID_EXTENSION_SETTINGS: {en: "Enter 1–50 extensions per type, each containing 1–16 letters or digits without a dot.", 'zh-CN': "每种类型请填写 1–50 个后缀，每个后缀使用 1–16 位字母或数字，不含点号。"},
  INVALID_REVISION: {en: "The page version is invalid. Reload and try again.", 'zh-CN': "页面版本信息无效，请刷新后重试。"},
  INVALID_FILE_TYPE: {en: "Choose a Working Paper, Amendment, or Draft Resolution.", 'zh-CN': "请选择工作文件、修正案或决议草案。"},
  COMMITTEE_READ_ONLY: {en: "This committee is archived or being deleted and cannot be edited.", 'zh-CN': "委员会已归档或正在删除，不能修改内容。"},
  STORAGE_NOT_CONFIGURED: {en: "File storage is not configured. Ask a Chair to configure it in file settings.", 'zh-CN': "尚未配置文件存储，请联系主席在文件设置中配置。"},
  MEETING_REQUIRED_FOR_SHARING: {en: "Start the first meeting session before sharing files.", 'zh-CN': "请先开始首个会期，再分享文件。"},
  DELEGATION_NOT_PRESENT: {en: "This delegation is unavailable in the current session. Check that its seat is enabled and marked present or temporarily away.", 'zh-CN': "该代表团不在当前会期的可用名单中，请检查席位是否启用，以及是否处于出席或暂离状态。"},
  FILE_NOT_PENDING_REVIEW: {en: "This file is no longer awaiting review. Refresh the file list.", 'zh-CN': "该文件已不在待审核状态，请刷新文件列表。"},
  FILE_CONTENT_UNAVAILABLE: {en: "File content is unavailable. Check its save or sync status.", 'zh-CN': "文件内容尚不可用，请检查保存或同步状态。"},
  INVALID_REJECTION_TYPE: {en: "Choose a rejection type from the current file settings.", 'zh-CN': "请选择当前文件设置中的驳回类型。"},
  CHAIR_OR_OWNER_REQUIRED: {en: "Chair or committee owner access is required.", 'zh-CN': "需要主席或委员会所有者权限。"},
  FILE_SHARING_UNAVAILABLE: {en: "File sharing has ended or is unavailable. Ask a Chair for a valid link.", 'zh-CN': "文件分享已结束或当前不可用，请向主席索取有效链接。"},
  FILE_SHARE_CUSTODIAN_UNAVAILABLE: {en: "The Chair who started file sharing is unavailable. Ask another Chair to restart sharing.", 'zh-CN': "发起文件分享的主席账号已不可用，请由其他主席重新开始分享。"},
  CACHE_LIMIT_INVALID: {en: "Cache settings exceed server limits. Lower the capacity limit or increase reserved space.", 'zh-CN': "缓存设置超出服务器允许范围，请降低容量上限或增加保留空间。"},
  OPERATIONS_UNAVAILABLE: {en: "Operations status could not be read. Refresh the operations page later.", 'zh-CN': "暂时无法读取运行状态，请稍后刷新运维页面。"},
  INVALID_DELETION_CONFIRMATION: {en: "Enter the full committee name to confirm deletion.", 'zh-CN': "请输入完整的委员会名称以确认删除。"},
  ARCHIVE_BEFORE_DELETE: {en: "Archive the committee before deleting it.", 'zh-CN': "请先归档委员会，再删除。"},
  COMMITTEE_NAME_MISMATCH: {en: "The confirmation does not match the committee name. Enter its full name.", 'zh-CN': "确认名称与委员会名称不一致，请输入完整名称。"},
  CHAIR_RECONNECT_BEFORE_DELETE: {en: "Reconnect the current Chair storage computer before deleting the committee.", 'zh-CN': "请先让当前主席存储电脑重新上线，再删除委员会。"},
  FILE_CLEANUP_METADATA_MISSING: {en: "File cleanup information is incomplete. Ask an administrator to check storage before deletion can finish.", 'zh-CN': "文件清理信息不完整，无法完成删除，请联系管理员检查文件存储。"},
  ARCHIVE_BEFORE_EXPORT: {en: "Archive the committee before exporting it.", 'zh-CN': "请先归档委员会，再导出。"},
  INVALID_STORAGE_PROVIDER: {en: "Choose server storage or S3 as the migration target.", 'zh-CN': "请选择服务器存储或 S3 作为迁移目标。"},
  SERVER_STORAGE_CONFIG_UNEXPECTED: {en: "Server storage does not use an S3 configuration. Select the storage type again.", 'zh-CN': "服务器存储不需要 S3 配置，请重新选择存储方式。"},
  STORAGE_BINDING_UNAVAILABLE: {en: "The current storage configuration is unavailable. Refresh file settings and check storage status.", 'zh-CN': "当前存储配置已不可用，请刷新文件设置并检查存储状态。"},
  MIGRATION_NOT_RETRYABLE: {en: "Only a failed storage migration can be retried. Refresh its status.", 'zh-CN': "只有失败的存储迁移可以重试，请刷新迁移状态。"},
  MIGRATION_TARGET_UNAVAILABLE: {en: "The migration destination is unavailable. Check its configuration.", 'zh-CN': "迁移目标存储已不可用，请检查目标配置。"},
  MIGRATION_STORAGE_CHANGED: {en: "Storage changed during migration. Refresh and review the migration.", 'zh-CN': "迁移期间存储配置发生变化，请刷新并重新检查迁移。"},
  MIGRATION_NOT_VERIFIED: {en: "Destination files have not all been copied and verified. Wait for migration to finish.", 'zh-CN': "目标文件尚未全部复制并校验完成，请等待迁移完成。"},
  MIGRATION_NOT_CANCELLABLE: {en: "This migration is completed or cancelled and cannot be cancelled again.", 'zh-CN': "该迁移已完成或已取消，无法再次取消。"},
  MIGRATION_COPY_CONFLICT: {en: "A migration copy does not match its record. Ask an administrator to check the migration.", 'zh-CN': "迁移副本与记录不一致，请联系管理员检查迁移任务。"},
  STORAGE_ALREADY_ACTIVE: {en: "The selected storage is already active. Refresh file settings.", 'zh-CN': "所选存储已经启用，请刷新文件设置。"},
  S3_CONFIG_UNAVAILABLE: {en: "The S3 configuration is unavailable. Ask an administrator to check it.", 'zh-CN': "S3 配置已不可用，请联系管理员检查该配置。"},
  CHAIR_FILE_ONLY: {en: "This file is only on the Chair computer. Bring it online and wait for sync.", 'zh-CN': "文件仅保存在主席电脑，请让该电脑上线并等待同步。"},
  FILE_OWNER_OR_CHAIR_REQUIRED: {en: "Only the file owner, committee owner, or a Chair can change this file.", 'zh-CN': "只有文件所属账号、委员会所有者或主席可以修改此文件。"},
  FILE_STATE_CHANGED: {en: "The file state changed and no longer permits this action. Refresh the file list.", 'zh-CN': "文件状态已变化，不能执行此操作，请刷新文件列表。"},
  FILE_REVIEW_REQUIRED: {en: "Approve this file in file review.", 'zh-CN': "请在文件审核中批准此文件。"},
  INVALID_S3_CREDENTIALS: {en: "Enter a valid S3 access key and secret key.", 'zh-CN': "请填写有效的 S3 访问密钥和私密密钥。"},
  STORAGE_ENCRYPTION_NOT_CONFIGURED: {en: "Storage credential encryption is not configured. Ask an administrator to configure it.", 'zh-CN': "服务器尚未配置存储凭据加密，请联系管理员完成配置。"},
  STORAGE_CREDENTIALS_UNREADABLE: {en: "Storage credentials cannot be decrypted. Ask an administrator to check the encryption key or save the credentials again.", 'zh-CN': "服务器无法解密存储凭据，请联系管理员检查加密密钥或重新保存凭据。"},
  STORAGE_CAPACITY_UNAVAILABLE: {en: "Available storage space could not be read. Ask an administrator to check the storage volume.", 'zh-CN': "无法读取存储剩余空间，请联系管理员检查存储卷。"},
  STORAGE_CAPACITY_LOW: {en: "Storage space is low. Free space or increase capacity before retrying.", 'zh-CN': "存储空间不足，请清理文件或扩容后重试。"},
  CACHE_FULL: {en: "The download cache is full. Ask an administrator to free cache space or increase its limit.", 'zh-CN': "下载缓存已满，请联系管理员清理缓存或提高缓存容量。"},
  REVIEW_STORAGE_FULL: {en: "Pending review storage is full. Review pending files or increase capacity first.", 'zh-CN': "待审核文件空间已满，请先处理待审核文件或增加容量。"},
  STORAGE_RESERVE_REQUIRED: {en: "Saving this file would use reserved disk space. Free space or increase storage capacity.", 'zh-CN': "保存文件会占用服务器保留空间，请清理存储或扩容。"},
  INVALID_FILE_SIZE: {en: "The file size is invalid. Select the file again.", 'zh-CN': "文件大小无效，请重新选择文件。"},
  COMMITTEE_MEMBER_REQUIRED: {en: "Join this committee before performing this action.", 'zh-CN': "需要加入该委员会后才能执行此操作。"},
  UPLOAD_CREATOR_REQUIRED: {en: "Only the account that started the upload can continue it. Use that account or start a new upload.", 'zh-CN': "只有发起上传的账号可以继续该上传，请使用原账号或重新上传。"},
  UPLOAD_STATE_CHANGED: {en: "This upload is completed, cancelled, or expired. Refresh its status.", 'zh-CN': "该上传已完成、已取消或已过期，请刷新上传状态。"},
  INVALID_UPLOAD_TARGET: {en: "The target does not match a new file or an existing version. Select the file again.", 'zh-CN': "新建文件和追加版本的目标不匹配，请重新选择文件。"},
  UPLOAD_NOT_READY: {en: "File content has not finished uploading or verification. Wait before retrying.", 'zh-CN': "文件内容尚未上传或校验完成，请等待后重试。"},
  STORAGE_PROVIDER_CHANGED: {en: "The file storage provider changed. Refresh and upload again.", 'zh-CN': "文件存储方式已变化，请刷新后重新上传。"},
  S3_ADDRESS_BLOCKED: {en: "The S3 address points to a blocked network. Check the address and server network settings.", 'zh-CN': "S3 地址指向不允许访问的网络，请检查地址及服务器网络设置。"},
  INVALID_S3_ENDPOINT: {en: "Enter a valid S3 HTTPS endpoint.", 'zh-CN': "请输入有效的 S3 HTTPS 地址。"},
  INVALID_S3_ENDPOINT_FORMAT: {en: "The S3 endpoint must use HTTPS and contain no credentials, query parameters, or fragment.", 'zh-CN': "S3 地址必须使用 HTTPS，且不能包含账号、密码、查询参数或片段。"},
  INVALID_S3_BUCKET: {en: "Enter a valid S3 bucket name.", 'zh-CN': "请填写有效的 S3 存储桶名称。"},
  INVALID_S3_REGION: {en: "Enter a valid S3 region.", 'zh-CN': "请填写有效的 S3 区域名称。"},
  INVALID_S3_PREFIX: {en: "The S3 prefix is invalid. Remove parent-directory traversal and unsafe characters.", 'zh-CN': "S3 路径前缀无效，请去除上级目录跳转和不安全字符。"},
  INVALID_S3_OPTIONS: {en: "Check the S3 addressing and private-network options.", 'zh-CN': "请检查 S3 寻址方式和私有网络选项。"},
  INVALID_PROVIDER_STATUS: {en: "The storage configuration status is invalid. Refresh the configuration list.", 'zh-CN': "存储配置状态无效，请刷新配置列表。"},
  S3_VERIFICATION_FAILED: {en: "The S3 read/write test failed. Check the endpoint, bucket, credentials, and permissions.", 'zh-CN': "无法读写 S3 测试文件，请检查地址、存储桶、凭据和访问权限。"},
  S3_CONFIG_CHANGED: {en: "The S3 configuration changed. Refresh and upload again.", 'zh-CN': "S3 配置已变化，请刷新后重新上传。"},
  CHAIR_STORAGE_UNAVAILABLE: {en: "Chair computer storage is unavailable. Check its connection and pairing status.", 'zh-CN': "主席电脑存储暂不可用，请检查电脑连接和配对状态。"},
  AGENT_TASK_CLAIM_LOST: {en: "Another connection took over the sync task. Reconnect the Chair Agent.", 'zh-CN': "同步任务已由其他连接接管，请重新连接主席 Agent。"},
  AGENT_TASK_ALREADY_CLAIMED: {en: "The sync task is already claimed. Wait for the current sync to finish.", 'zh-CN': "同步任务已被领取，请等待当前同步完成。"},
  AGENT_TASK_NOT_AVAILABLE: {en: "The sync task is no longer pending. Refresh sync status.", 'zh-CN': "同步任务已不再等待处理，请刷新同步状态。"},
  AGENT_TASK_CONTENT_MISMATCH: {en: "Sync content does not match the task. Sync the file again.", 'zh-CN': "同步内容与任务不匹配，请重新同步该文件。"},
  AGENT_TASK_CONTENT_UNEXPECTED: {en: "This sync task no longer accepts content. Refresh sync status.", 'zh-CN': "该同步任务已不再接收内容，请刷新同步状态。"},
  FILE_INTEGRITY_FAILED: {en: "File verification failed. Upload or sync the file again.", 'zh-CN': "文件校验失败，请重新上传或同步文件。"},
  AGENT_CONTENT_NOT_STAGED: {en: "The sync file has not been staged. Sync it again.", 'zh-CN': "同步文件尚未保存到暂存区，请重新同步。"},
  AGENT_CONTENT_ALREADY_VERIFIED: {en: "The sync file is already verified. Refresh task status.", 'zh-CN': "同步文件已校验完成，请刷新任务状态。"},
  INVALID_PAIRING_PURPOSE: {en: "Choose initial pairing or transfer to another Chair computer.", 'zh-CN': "请选择首次配对或转移主席电脑。"},
  INVALID_DEVICE_LABEL: {en: "Enter a valid device name.", 'zh-CN': "请填写有效的设备名称。"},
  INVALID_DEVICE_KEY: {en: "The device identity is invalid. Create a new pairing request.", 'zh-CN': "设备身份信息无效，请重新生成配对请求。"},
  CHAIR_HOST_ALREADY_PAIRED: {en: "A Chair computer is already paired. Use transfer to replace it.", 'zh-CN': "委员会已经配对主席电脑，请使用转移功能更换电脑。"},
  CHAIR_PAIRING_STATE_CHANGED: {en: "The Chair computer changed during pairing. Refresh and generate a new pairing code.", 'zh-CN': "配对期间主席电脑状态已变化，请刷新并重新生成配对码。"},
  CHAIR_HOST_REVOKED: {en: "This Chair computer was unpaired or replaced. Pair it again.", 'zh-CN': "该主席电脑已解除配对或已被替换，请重新配对。"},
  AGENT_UPGRADE_REQUIRED: {en: "The Chair Agent capabilities are incompatible. Upgrade it and reconnect.", 'zh-CN': "主席 Agent 功能版本不兼容，请升级后重新连接。"},
  INVALID_CONFLICT_CONTENT: {en: "The conflict resolution content is invalid. Select the file again.", 'zh-CN': "用于解决冲突的文件内容无效，请重新选择文件。"},
  LOCAL_FILE_CONFLICT: {en: "The local file conflicts with the server. Choose how to resolve it in the file conflict list.", 'zh-CN': "本机文件与服务器记录冲突，请在文件冲突列表中选择保留方式。"},
  INVALID_CONFLICT_CHOICE: {en: "Choose a resolution available for this conflict.", 'zh-CN': "请选择当前冲突允许的解决方式。"},
  INVALID_FILE_NAME: {en: "Enter a valid file name.", 'zh-CN': "请输入有效的文件名称。"},
  UNSAFE_FILE_NAME: {en: "File names cannot contain absolute paths, parent-directory traversal, or reserved names.", 'zh-CN': "文件名不能包含绝对路径、上级目录跳转或系统保留名称。"},
  REVOKED_HOST_CONTENT: {en: "The original Chair computer was unpaired. Upload the content again using the current computer.", 'zh-CN': "原主席电脑已解除配对，不能采用其内容，请通过当前电脑重新上传。"},
  DELETED_FILE_REQUIRES_NEW: {en: "This file was deleted. Save the content as a new file.", 'zh-CN': "该文件已删除，请将需要保留的内容另存为新文件。"},
  LOCAL_COPY_REQUIRED: {en: "Only local file content can be saved as a new file.", 'zh-CN': "只有本机文件内容可以另存为新文件。"},
  CACHE_REFILL_INCOMPLETE: {en: "The file cache is not ready. Wait for the Chair computer to sync.", 'zh-CN': "文件缓存尚未准备完成，请等待主席电脑同步。"},
  UPLOAD_ACCOUNT_INACTIVE: {en: "The upload account is inactive. Upload again using an active account.", 'zh-CN': "发起上传的账号已停用，请使用活动账号重新上传。"},
  INVALID_THEME_SETTINGS: {en: "Theme settings are invalid. Select the theme setting again.", 'zh-CN': "主题设置格式无效，请重新选择主题开关。"},
  INVALID_COMMITTEE_DEFAULTS: {en: "Check the default operation mode and Chair assignment settings.", 'zh-CN': "请检查默认运作模式和主席权限设置。"},
  INSTANCE_ALREADY_INITIALIZED: {en: "This instance is already initialized. Sign in instead.", 'zh-CN': "系统已经初始化，请前往登录。"},
  INVALID_BOOTSTRAP_SECRET: {en: "The initialization secret is incorrect. Check the secret provided by the server.", 'zh-CN': "初始化密钥不正确，请检查服务器提供的密钥。"},
  INVALID_MOTION_DURATION: {en: "Enter a motion duration within the limits allowed by the rules.", 'zh-CN': "请填写规则允许范围内的动议时长。"},
  INVALID_DOCUMENT_ACTION: {en: "The document action is invalid. Refresh the document page.", 'zh-CN': "文书操作无效，请刷新文书页面。"},
  DOCUMENT_ACTION_RULE_BLOCKED: {en: "The rules for this document do not allow this action. Check the rule settings.", 'zh-CN': "当前文书适用的规则不允许此操作，请检查规则设置。"},
  CHAIR_OPERATED_ACTION: {en: "A Chair must perform this action in Chair-operated mode.", 'zh-CN': "主席代办模式下需要由主席执行此操作。"},
  OWN_SEAT_ONLY: {en: "Delegates can only act for their own seat.", 'zh-CN': "代表只能为自己的席位操作。"},
  ACTIVE_SEAT_REQUIRED: {en: "Assign an active seat to this account first.", 'zh-CN': "请先为账号分配活动席位。"},
  SEAT_NOT_PRESENT: {en: "This seat is not present. Update attendance first.", 'zh-CN': "该席位当前未出席，请先更新出席状态。"},
  INVALID_TIMER_OWNER: {en: "The timer owner is invalid. Reload and select it again.", 'zh-CN': "计时器关联对象无效，请刷新页面后重新选择。"},
  TIMER_ALREADY_RUNNING: {en: "The timer is already running.", 'zh-CN': "计时器已经在运行。"},
  TIMER_EXHAUSTED: {en: "Time has run out. Reset or extend the timer first.", 'zh-CN': "时间已用尽，请先重置或延长计时器。"},
  TIMER_NOT_RUNNING: {en: "The timer has not started or is paused. Refresh its status.", 'zh-CN': "计时器尚未运行或已经暂停，请刷新计时状态。"},
  TIMER_NOT_EXPIRED: {en: "The timer has not expired. Wait for it to finish.", 'zh-CN': "计时器尚未结束，请等待时间用尽。"},
  INVALID_SPEAKER_LIST_KIND: {en: "Choose a General Speaker's List or Moderated Caucus.", 'zh-CN': "请选择主发言名单或有主持核心磋商。"},
  INVALID_DELEGATE_QUEUE_SETTING: {en: "Select whether delegates may join the queue themselves.", 'zh-CN': "请重新选择是否允许代表自行加入名单。"},
  CAUCUS_SHORTER_THAN_SPEECH: {en: "The caucus duration must allow one complete speech.", 'zh-CN': "磋商总时长不能短于一次发言时间。"},
  MEETING_CLOSED: {en: "This meeting session is closed. Start or select an open session first.", 'zh-CN': "该会期已结束，请先开始或选择开放的会期。"},
  GENERAL_LIST_ALREADY_EXISTS: {en: "This session already has a General Speaker's List. Open the existing list.", 'zh-CN': "该会期已有主发言名单，请打开现有名单。"},
  SPEAKER_SETTINGS_UNCHANGED: {en: "The speaker list settings are unchanged.", 'zh-CN': "发言名单设置没有变化。"},
  INVALID_SPEAKER_LIST_STATUS: {en: "The speaker list status is invalid. Refresh and try again.", 'zh-CN': "发言名单状态无效，请刷新页面后重新操作。"},
  INVALID_SPEAKER_STANCE: {en: "Choose a supported speaker stance.", 'zh-CN': "请选择支持、中立或反对立场。"},
  SPEAKER_LIST_CLOSED: {en: "The speaker list is closed. Open it first.", 'zh-CN': "发言名单已关闭，请先开放名单。"},
  DELEGATE_QUEUE_DISABLED: {en: "Delegates cannot join this list themselves. Ask a Chair to add you.", 'zh-CN': "该名单未允许代表自行加入，请联系主席添加。"},
  PRESENT_SEAT_REQUIRED: {en: "Only a present active seat can perform this action. Update attendance first.", 'zh-CN': "只有当前出席的活动席位可以执行此操作，请先更新出席状态。"},
  SPEAKER_NO_LONGER_QUEUED: {en: "This seat is no longer waiting or speaking. Refresh the list.", 'zh-CN': "该席位已不在等待或当前发言名单中，请刷新名单。"},
  INVALID_QUEUE_ORDER: {en: "The order must include each waiting speaker exactly once.", 'zh-CN': "排序必须包含全部等待发言席位，且每个席位只能出现一次。"},
  PAUSE_SPEECH_FIRST: {en: "Pause the current speech before advancing to the next speaker.", 'zh-CN': "请先暂停当前发言，再切换到下一位。"},
  COMPLETE_SPEECH_FIRST: {en: "Complete the current speech before advancing to the next speaker.", 'zh-CN': "请先完成当前发言，再切换到下一位。"},
  NO_CURRENT_SPEAKER: {en: "There is no current speaker. Select the next speaker from the list first.", 'zh-CN': "当前没有发言席位，请先从名单选择下一位。"},
  SPEECH_ALREADY_ACTIVE: {en: "A speech is already active. Complete it first.", 'zh-CN': "已有进行中的发言，请先完成该发言。"},
  SPEECH_TIMERS_NOT_READY: {en: "The speech or caucus timer cannot start. Check the remaining time and reset or extend it.", 'zh-CN': "发言或磋商计时器无法启动，请检查剩余时间并重置或延长。"},
  CURRENT_SPEAKER_CHANGED: {en: "The current speaker changed. Refresh the list.", 'zh-CN': "当前发言席位已变化，请刷新名单。"},
  NO_ACTIVE_SPEECH: {en: "There is no active speech. Start a speech first.", 'zh-CN': "当前没有进行中的发言，请先开始发言。"},
  SPEECH_NOT_RUNNING: {en: "The speech has not started or is paused.", 'zh-CN': "当前发言尚未开始或已经暂停。"},
  SPEECH_CANNOT_RESUME: {en: "This speech cannot resume. Check whether it has ended and whether time remains.", 'zh-CN': "当前发言不能继续，请检查是否已结束及剩余时间。"},
  SPEECH_ALREADY_COMPLETE: {en: "This speech is already complete. Refresh the list.", 'zh-CN': "该发言已完成，请刷新名单。"},
  INVALID_YIELD_TYPE: {en: "Choose a yield type allowed by the current rules.", 'zh-CN': "请选择当前规则允许的让渡方式。"},
  YIELD_TO_SELF: {en: "You cannot yield to yourself. Select another present seat.", 'zh-CN': "不能把发言时间让渡给自己，请选择其他出席席位。"},
  YIELD_TARGET_UNEXPECTED: {en: "This yield type does not use a target seat.", 'zh-CN': "该让渡方式不需要指定接收席位。"},
  INVALID_YIELD_DECISION: {en: "Choose whether to accept or reject this yield.", 'zh-CN': "请选择接受或拒绝此次让渡。"},
  NO_PENDING_YIELD: {en: "There is no pending delegate yield to decide.", 'zh-CN': "当前没有等待裁定的代表让渡请求。"},
  INVALID_CONTRIBUTION_TYPE: {en: "Choose a question or comment.", 'zh-CN': "请选择提问或评论。"},
  CONTRIBUTION_NOT_ALLOWED: {en: "This speech does not accept that question or comment. Check the yield type.", 'zh-CN': "当前发言不接受这种提问或评论，请检查让渡方式。"},
  INVALID_SEAT_REFERENCE: {en: "The selected seat is invalid. Refresh and select it again.", 'zh-CN': "所选席位无效，请刷新后重新选择。"},
  INVALID_MOTION_PARAMETERS: {en: "Motion parameters do not match the current rules. Check the type, duration, and target.", 'zh-CN': "动议参数不符合当前规则，请检查动议类型、时长和目标。"},
  MOTION_TYPE_UNAVAILABLE: {en: "This motion type is not in the current session rules. Select another motion.", 'zh-CN': "该动议类型不在当前会期规则中，请重新选择动议。"},
  INVALID_SECOND_REQUIREMENT: {en: "The required seconder count is invalid. Check the motion rules.", 'zh-CN': "动议附议数量不符合规则，请检查动议规则。"},
  CHAIR_REQUIRED: {en: "Chair access is required.", 'zh-CN': "需要主席权限。"},
  MOTION_NO_SECONDS_REQUIRED: {en: "This motion does not require seconds.", 'zh-CN': "该动议不需要附议。"},
  INVALID_DOCUMENT_COUNTRIES: {en: "Select a list of distinct countries.", 'zh-CN': "请选择不重复的国家。"},
  DOCUMENT_COUNTRY_ROLES_OVERLAP: {en: "Drafting and seconding countries must be different.", 'zh-CN': "同一国家不能同时列为起草国和附议国。"},
  AMENDMENT_PROPOSER_REQUIRED: {en: "Select one Amendment proposer.", 'zh-CN': "请选择一个修正案提案国。"},
  PROPOSER_SECONDER_SAME: {en: "The proposer and seconder must be different seats.", 'zh-CN': "提案国与附议国必须是不同席位。"},
  MOTION_SECONDS_CLOSED: {en: "This motion no longer accepts seconds. Refresh the motion list.", 'zh-CN': "该动议已不再接受附议，请刷新动议列表。"},
  MEETING_NOT_OPEN: {en: "Start a meeting session before performing this action.", 'zh-CN': "请先开始会期，再执行此操作。"},
  ROLL_CALL_MUST_FINISH: {en: "Complete or reset the active Roll Call first.", 'zh-CN': "请先完成或重置正在进行的点名。"},
  MEETING_ALREADY_PENDING: {en: "A meeting session is already pending. Start the existing session.", 'zh-CN': "已有待开始的会期，请开始现有会期。"},
  GENERAL_SPEAKER_LIST_MISSING: {en: "This session has no General Speaker's List. A Chair must confirm creation of a replacement.", 'zh-CN': "该会期缺少主发言名单，请由主席确认创建替代名单。"},
  UNMODERATED_TIMER_MISSING: {en: "There is no Unmoderated Caucus timer to extend. Start an Unmoderated Caucus first.", 'zh-CN': "当前没有可延长的自由磋商计时器，请先开始自由磋商。"},
  CAUCUS_DURATION_NOT_DIVISIBLE: {en: "The caucus duration must be evenly divisible by the speech time.", 'zh-CN': "磋商总时长必须能被单次发言时间整除。"},
  RESOLUTION_NOT_INTRODUCED: {en: "Pass a motion to introduce this Draft Resolution first.", 'zh-CN': "请先通过展示该决议草案的动议。"},
  RESOLUTION_CAUCUS_EXISTS: {en: "This resolution already has a caucus. Open the existing caucus.", 'zh-CN': "该决议草案已有对应的磋商，请打开现有磋商。"},
  CAUCUS_CLOSED: {en: "The target caucus is closed. Select an open caucus.", 'zh-CN': "目标磋商已关闭，请选择开放的磋商。"},
  CAUCUS_TIMER_MISSING: {en: "The caucus timer is unavailable. Refresh, and contact an administrator if it remains unavailable.", 'zh-CN': "找不到该磋商的计时器，请刷新；仍不可用时联系管理员。"},
  RESOLUTION_ALREADY_INTRODUCED: {en: "Only an unintroduced Draft Resolution can be introduced. Refresh and select again.", 'zh-CN': "只能展示尚未展示的决议草案，请刷新后重新选择。"},
  AMENDMENT_ALREADY_INTRODUCED: {en: "Only a Draft Amendment can be introduced. Refresh and select again.", 'zh-CN': "只能展示尚未展示的修正案草案，请刷新后重新选择。"},
  AMENDMENT_BODY_REQUIRED: {en: "Add Amendment text or select a published file first.", 'zh-CN': "请先填写修正案正文或选择已发布文件。"},
  AMENDMENT_NOT_INTRODUCED: {en: "Pass a motion to introduce this Amendment first.", 'zh-CN': "请先通过展示该修正案的动议。"},
  INVALID_MOTION_RESULT: {en: "Choose a motion result allowed by the rules.", 'zh-CN': "请选择规则允许的动议结果。"},
  MOTION_ALREADY_DECIDED: {en: "This motion already has a result. Refresh the motion list.", 'zh-CN': "该动议已有结果，请刷新动议列表。"},
  MOTION_SECONDS_INSUFFICIENT: {en: "The motion has too few seconds. Obtain the required seconds first.", 'zh-CN': "附议数量未达到要求，请先补足附议。"},
  INVALID_NON_VOTING_SETTING: {en: "Select whether non-voting seats may participate.", 'zh-CN': "请重新选择是否允许无表决权席位投票。"},
  VOTE_SETTINGS_LOCKED: {en: "Delegates have started voting. These vote settings are locked.", 'zh-CN': "代表已开始投票，不能再修改本次表决设置。"},
  VOTE_SETTINGS_UNCHANGED: {en: "This vote setting is already selected.", 'zh-CN': "该表决设置已经选中。"},
  INVALID_VOTE_CHOICE: {en: "Choose a for, against, or abstain option allowed in this vote.", 'zh-CN': "请选择本次表决允许的赞成、反对或弃权选项。"},
  DELEGATE_VOTING_DISABLED: {en: "Delegate voting is disabled. Ask a Chair to record the vote.", 'zh-CN': "代表投票未启用，请由主席记录表决。"},
  SEAT_NOT_ELIGIBLE_TO_VOTE: {en: "This seat is not eligible for this vote. Check attendance and voting rights.", 'zh-CN': "该席位不具备本次表决资格，请检查出席状态和表决权。"},
  PROCEDURAL_ABSTENTION_FORBIDDEN: {en: "Procedural votes cannot abstain. Choose for or against.", 'zh-CN': "程序性表决不能弃权，请选择赞成或反对。"},
  NO_VOTE_TO_UNDO: {en: "This seat has no current vote to undo. Refresh the vote records.", 'zh-CN': "该席位当前没有可撤销的投票，请刷新表决记录。"},
  MOTION_NOT_WITHDRAWABLE: {en: "Only a pending motion can be withdrawn.", 'zh-CN': "只有待处理的动议可以撤回。"},
  INVALID_BALLOT_SUBJECT: {en: "The ballot subject is invalid. Select the motion or document again.", 'zh-CN': "表决对象无效，请重新选择动议或文书。"},
  INVALID_BALLOT_PROCEDURE: {en: "Select a procedural or substantive ballot.", 'zh-CN': "请重新选择程序性或实体性表决。"},
  INVALID_BALLOT_THRESHOLD: {en: "Choose a majority threshold for this ballot.", 'zh-CN': "请选择本次表决适用的多数门槛。"},
  MOTION_SESSION_MISMATCH: {en: "This motion belongs to another session. Select a motion in the current session.", 'zh-CN': "该动议属于其他会期，请选择当前会期的动议。"},
  MOTION_NOT_READY_FOR_VOTE: {en: "This motion is not ready for voting. Check its status and required seconds.", 'zh-CN': "该动议当前不能进入表决，请检查处理状态及附议数量。"},
  BALLOT_PROCEDURE_MISMATCH: {en: "The ballot procedure does not match this motion's rules. Select the procedure required by the rules.", 'zh-CN': "表决类型与该动议适用的规则不一致，请按规则选择。"},
  BALLOT_ALREADY_EXISTS: {en: "This motion already has a ballot. Open the existing ballot.", 'zh-CN': "该动议已有正式表决，请打开现有表决。"},
  DOCUMENT_NOT_IN_VOTING: {en: "This document has not entered formal voting. Pass the required voting motion first.", 'zh-CN': "该文书尚未进入正式表决，请先通过相关表决动议。"},
  NO_ELIGIBLE_VOTERS: {en: "This ballot has no eligible seats. Check attendance and voting rights.", 'zh-CN': "本次表决没有合资格席位，请检查出席状态和表决权。"},
  BALLOT_NOT_OPEN: {en: "This ballot is not open or has ended. Refresh its status.", 'zh-CN': "该表决尚未开始或已经结束，请刷新表决状态。"},
  VOTE_CHOICE_NOT_ALLOWED: {en: "This seat cannot cast that choice. Check the ballot's abstention restrictions.", 'zh-CN': "该席位不能选择此选项，请检查本次表决的弃权限制。"},
  INVALID_VOTE_CORRECTION: {en: "Select a vote allowed for this seat and enter a correction reason.", 'zh-CN': "请选择该席位允许的投票选项，并填写更正理由。"},
  VOTE_ALREADY_RECORDED: {en: "This vote is already recorded for the seat. Refresh to see the result.", 'zh-CN': "该席位的相同投票已记录，请刷新查看结果。"},
  REQUIRED_VOTES_MISSING: {en: "Required eligible seats have not all voted. Record their votes first.", 'zh-CN': "仍有本次规则要求投票的合资格席位未投票，请先完成这些席位的投票。"},
  CLOSE_BALLOT_FIRST: {en: "Close the ballot before publishing its result.", 'zh-CN': "请先结束表决，再发布结果。"},
  BALLOT_MOTION_ALREADY_DECIDED: {en: "The motion is no longer awaiting a result. Refresh the motion and ballot status.", 'zh-CN': "对应动议已不再等待结果，请刷新动议和表决状态。"},
  INVALID_POLL_VOTING_MODE: {en: "Choose seat-authenticated or anonymous voting.", 'zh-CN': "请选择实名或匿名投票。"},
  INVALID_POLL_CHOICE_MODE: {en: "Choose single-choice or multiple-choice voting.", 'zh-CN': "请选择单选或多选。"},
  INVALID_POLL_OPTIONS: {en: "Enter valid Strawpoll options.", 'zh-CN': "请填写有效的意向性投票选项。"},
  INVALID_POLL_MEDIUM: {en: "Choose linked voting or manual tallying.", 'zh-CN': "请选择链接投票或手动计票。"},
  INVALID_POLL_OPTION_PERMISSION: {en: "Select whether delegates may add options.", 'zh-CN': "请重新选择是否允许代表添加选项。"},
  POLL_OPTIONS_DUPLICATED: {en: "Poll options must be unique. Change duplicate options.", 'zh-CN': "投票选项不能重复，请修改重复选项。"},
  MANUAL_POLL_CANNOT_BE_ANONYMOUS: {en: "Manual tallying does not support anonymous voting. Change the voting mode.", 'zh-CN': "手动计票不支持匿名投票，请更改投票方式。"},
  POLL_NOT_ACCEPTING_LINKED_VOTES: {en: "This poll is not accepting linked votes. Refresh and check the voting method.", 'zh-CN': "该投票未开放链接投票，请刷新并检查投票方式。"},
  POLL_SINGLE_CHOICE_REQUIRED: {en: "Select exactly one option for this poll.", 'zh-CN': "本次投票只能选择一个选项。"},
  POLL_OPTION_UNAVAILABLE: {en: "The selected poll option is unavailable. Refresh and select again.", 'zh-CN': "所选投票选项已不可用，请刷新后重新选择。"},
  ANONYMOUS_VOTE_NOT_RETRACTABLE: {en: "An anonymous vote cannot be retracted after submission.", 'zh-CN': "匿名投票提交后不能撤回。"},
  POLL_MODE_MISMATCH: {en: "The poll's identity mode changed. Refresh the voting page.", 'zh-CN': "本次投票的身份方式已变化，请刷新投票页面。"},
  ANONYMOUS_POLL_ACCESS_INVALID: {en: "The anonymous voting credential is invalid. Reopen the voting link.", 'zh-CN': "匿名投票凭据无效，请重新打开投票链接。"},
  POLL_NOT_VOTING: {en: "The Strawpoll has not started or has ended. Refresh its status.", 'zh-CN': "意向性投票尚未开始或已经结束，请刷新投票状态。"},
  INVALID_POLL_CONFIGURATION: {en: "The voting method and identity settings do not match. Select them again.", 'zh-CN': "投票方式与身份设置不匹配，请重新选择。"},
  POLL_ROUND_CHANGED: {en: "This poll round ended or was replaced by a new round. Refresh the page.", 'zh-CN': "该轮投票已结束或已被新一轮替代，请刷新页面。"},
  DELEGATE_OPTION_LIMIT: {en: "Delegates may add one option at a time and cannot change existing options.", 'zh-CN': "代表每次只能添加一个选项，不能修改已有选项。"},
  INVALID_POLL_ACTION: {en: "The poll stage action is invalid. Refresh the poll page.", 'zh-CN': "投票阶段操作无效，请刷新投票页面。"},
  POLL_STAGE_CHANGED: {en: "The poll stage changed. Refresh and use the actions for its current stage.", 'zh-CN': "投票阶段已变化，请刷新后按当前阶段操作。"},
  POLL_QUESTION_REQUIRED: {en: "Enter a poll question first.", 'zh-CN': "请先填写投票题目。"},
  POLL_OPTIONS_REQUIRED: {en: "At least two options are required to start voting.", 'zh-CN': "至少需要两个选项才能开始投票。"},
  INVALID_MANUAL_TALLY: {en: "Vote counts must be non-negative integers.", 'zh-CN': "票数必须是非负整数。"},
  POLL_NOT_ACCEPTING_TALLIES: {en: "This poll is not accepting manual tallies. Check its stage and voting method.", 'zh-CN': "该投票当前未开放手动计票，请检查阶段和投票方式。"},
  TALLY_UNCHANGED: {en: "The vote count for this option is unchanged.", 'zh-CN': "该选项的票数没有变化。"},
  AMENDMENT_PROPOSER_OR_CHAIR_REQUIRED: {en: "Only the Amendment proposer or a Chair can delete it.", 'zh-CN': "只有修正案提案国或主席可以删除该修正案。"},
  AMENDMENT_VOTING_STARTED: {en: "Voting has begun for this Amendment. It cannot be deleted.", 'zh-CN': "修正案已开始表决，不能删除。"},
  DOCUMENT_SESSION_MISMATCH: {en: "The Amendment and Draft Resolution must belong to the same meeting session.", 'zh-CN': "修正案必须与决议草案属于同一会期。"},
  AMENDMENTS_NOT_ACCEPTED: {en: "This Draft Resolution does not currently accept Amendments. Check its status and Amendment settings.", 'zh-CN': "该决议草案当前不接受修正案，请检查状态和修正案设置。"},
  FORMAL_DEBATE_CLOSED: {en: "Formal Debate has ended. Reopen it to introduce an Amendment.", 'zh-CN': "正式辩论已结束；重新开启后才可介绍修正案。"},
  DOCUMENT_BODY_SOURCE_CONFLICT: {en: "Use either text or one file for the document body.", 'zh-CN': "正文只能使用文本或一个文件，请选择其中一种。"},
  DOCUMENT_FROZEN: {en: "This document has entered voting or has a result. Its version cannot be edited.", 'zh-CN': "文书已进入表决或已产生结果，不能再修改版本。"},
  DOCUMENT_PROPOSER_OR_CHAIR_REQUIRED: {en: "Only the proposer or a Chair can edit this document.", 'zh-CN': "只有提案国或主席可以修改此文书。"},
  DOCUMENT_INTRODUCTION_MOTION_REQUIRED: {en: "Introduce the document through a passed motion; its status cannot be changed directly.", 'zh-CN': "请通过展示文书的动议，不能直接更改为已展示状态。"},
  DOCUMENT_STATE_CHANGED: {en: "The document state changed. Refresh and check the available actions.", 'zh-CN': "文书状态已变化，请刷新后检查当前可用操作。"},
  DOCUMENT_SETTINGS_EMPTY: {en: "Select a document setting to change.", 'zh-CN': "请选择需要修改的文书设置。"},
  RESOLUTION_SETTING_ONLY: {en: "This setting is available for Draft Resolutions, not Amendments.", 'zh-CN': "此设置仅适用于决议草案，不适用于修正案。"},
  INVALID_AMENDMENT_SETTING: {en: "Select whether delegates may propose Amendments.", 'zh-CN': "请重新选择是否允许代表提出修正案。"},
  DOCUMENT_SETTINGS_UNCHANGED: {en: "The document settings are unchanged.", 'zh-CN': "文书设置没有变化。"},
  SEAT_MUST_VOTE: {en: "This seat cannot abstain. Choose for or against.", 'zh-CN': "该席位不得弃权，请选择赞成或反对。"},
  INVALID_DOCUMENT_RESULT: {en: "Choose a result allowed for this document.", 'zh-CN': "请选择该文书允许的结果。"},
  AMENDMENT_BALLOT_RESULT_REQUIRED: {en: "This Amendment has a Formal Ballot. Publish its ballot result to record the outcome.", 'zh-CN': "该修正案已有正式表决，请通过发布表决结果记录结论。"},
  RESULT_ALREADY_RECORDED: {en: "This result is already recorded. Refresh to see it.", 'zh-CN': "相同结果已经记录，请刷新查看。"},
  CORRECTION_REASON_REQUIRED: {en: "Enter a correction reason.", 'zh-CN': "请填写更正理由。"},
  INITIAL_RESULT_CORRECTION_UNEXPECTED: {en: "An initial result does not use a correction reason.", 'zh-CN': "首次记录结果不需要更正理由。"},
  DOCUMENT_DISCUSSION_CLOSED: {en: "This document has not been introduced or is no longer open for discussion.", 'zh-CN': "该文书尚未展示或已不再开放讨论。"},
  ASSIGNMENT_OR_KEY_EXISTS: {en: "The seat assignment or resource key already exists. Check for duplicate records.", 'zh-CN': "账号席位分配或资源标识已存在，请检查重复记录。"},
  INVALID_REFERENCE: {en: "The selected reference is unavailable or belongs to another resource. Refresh and select again.", 'zh-CN': "所选内容已不可用或不属于当前对象，请刷新后重新选择。"},
  OWNER_REQUIRED: {en: "Committee owner access is required.", 'zh-CN': "需要委员会所有者权限。"},
  INVALID_RULE_PATH: {en: "The rule field path is invalid. Select a configurable field.", 'zh-CN': "规则字段路径无效，请从可配置字段中选择。"},
  RULE_PATH_NOT_CONFIGURABLE: {en: "This rule field cannot be overridden. Select a configurable field.", 'zh-CN': "该规则字段不允许覆盖，请选择可配置字段。"},
  INVALID_RULE_PACKAGE: {en: "The rule package does not match the required format. Check its definition.", 'zh-CN': "规则包内容不符合格式要求，请检查规则定义。"},
  INVALID_RULE_INHERITANCE: {en: "The rule inheritance is invalid. Check the parent package and version.", 'zh-CN': "规则包继承关系无效，请检查父规则包和版本。"},
  UNSUPPORTED_FIELDS: {en: "The request contains unsupported fields. Reload the page and try again.", 'zh-CN': "请求包含当前版本不支持的字段，请刷新页面后重试。"},
  INVALID_VISIBILITY: {en: "Choose a public or private committee.", 'zh-CN': "请选择公开或私有委员会。"},
  ADMIN_CANNOT_BE_CHAIR: {en: "The system administrator cannot be a Chair. Choose a regular account.", 'zh-CN': "系统管理员账号不能担任主席，请选择普通账号。"},
  INVALID_OPERATION_MODE: {en: "Choose Chair-operated or delegate-operated mode.", 'zh-CN': "请选择主席代办或代表自主模式。"},
  INVALID_MOTION_SETTINGS: {en: "Motion settings are invalid. Select the motion options again.", 'zh-CN': "动议设置格式无效，请重新选择动议选项。"},
  INVALID_LAYOUT_SETTINGS: {en: "Layout settings are invalid. Select the layout options again.", 'zh-CN': "布局设置格式无效，请重新选择布局选项。"},
  INVALID_COMMITTEE_STATUS: {en: "The committee status is invalid. Refresh and try again.", 'zh-CN': "委员会状态无效，请刷新后重新操作。"},
  INVALID_INVITATION_LIMITS: {en: "The invitation expiry and use count must be within the allowed limits.", 'zh-CN': "邀请有效期和使用次数必须在允许范围内。"},
  ACCOUNT_ALREADY_ASSIGNED: {en: "This account already has an active seat in this committee. Remove the existing assignment first.", 'zh-CN': "该账号已在本委员会分配活动席位，请先取消原分配。"},
  INVALID_RULE_SCOPE: {en: "The rule package scope is invalid. Select a system or account rule package.", 'zh-CN': "规则包范围无效，请选择系统或账号规则包。"},
  BUILTIN_RULE_IMMUTABLE: {en: "Built-in rule packages cannot be edited. Clone the package first.", 'zh-CN': "内置规则包不能修改，请先克隆。"},
  INVALID_SIMULATION_FACTS: {en: "Simulation inputs are invalid. Check attendance, voting rights, and other conditions.", 'zh-CN': "规则模拟输入无效，请检查人数、表决权等条件。"},
  RULE_SIMULATION_FAILED: {en: "The simulation could not compute a result. Check the expressions and inputs.", 'zh-CN': "规则模拟无法计算结果，请检查表达式和输入条件。"},
  RULE_VERSION_NOT_PUBLISHED: {en: "The selected rule version is not published. Publish it or choose a published version.", 'zh-CN': "所选规则版本尚未发布，请先发布或选择已发布版本。"},
  INVALID_RULE_VERSION: {en: "The selected rule version is invalid. Refresh and select again.", 'zh-CN': "所选规则版本无效，请刷新后重新选择。"},
  INVALID_RULE_OVERRIDE_SCOPE: {en: "Select whether the rule override applies to this session or future sessions.", 'zh-CN': "请选择本会期或后续会期的规则覆盖范围。"},
  ACTIVE_RULES_UNAVAILABLE: {en: "The active rules are unavailable. Ask a Chair to check the active rule version.", 'zh-CN': "当前规则无法读取，请联系主席检查活动规则版本。"},
  INVALID_RULE_OVERRIDE: {en: "The override makes the rule package invalid. Check the values and rule constraints.", 'zh-CN': "规则覆盖使规则包无效，请检查覆盖值和规则约束。"},
  REQUEST_TOO_LARGE: {en: "The submitted content exceeds the server limit. Reduce it and try again.", 'zh-CN': "提交内容超过服务器限制，请减少内容后重试。"},
  INVALID_REQUEST_BODY: {en: "The request format is invalid. Reload the page and submit again.", 'zh-CN': "请求格式无效，请刷新页面后重新提交。"},
  ORIGIN_NOT_ALLOWED: {en: "This site address is not allowed by the server. Use the address provided by the administrator.", 'zh-CN': "当前访问地址未获服务器允许，请使用管理员提供的站点地址。"},
  DELEGATION_ALREADY_SELECTED: {en: "This browser already selected a delegation. Continue with that delegation.", 'zh-CN': "此浏览器已选择代表团，请继续使用已选代表团。"},
  CSRF_EXPIRED: {en: "The page verification token expired. Reload the page and try again.", 'zh-CN': "页面验证信息已失效，请刷新页面后重新操作。"},
  EVENT_CURSOR_AHEAD: {en: "The live update position does not match the server. Reload to reconnect.", 'zh-CN': "实时更新位置与服务器不一致，请刷新页面重新连接。"},
  INVALID_CONTENT: {en: "The content format or length is invalid. Check the entered text.", 'zh-CN': "正文格式或长度不符合要求，请检查输入内容。"},
  INVALID_SORT_ORDER: {en: "The sort order must be an integer.", 'zh-CN': "排序值必须是整数。"},
  POINT_RULE_UNAVAILABLE: {en: "This point is missing from the current rules. Ask a Chair to check the rules.", 'zh-CN': "当前规则中缺少该问题的定义，请联系主席检查规则。"},
  INVALID_COUNTRY_TEMPLATE: {en: "Select a valid country template.", 'zh-CN': "请选择有效的国家模板。"},
  BUILTIN_TEMPLATE_IMMUTABLE: {en: "Built-in templates cannot be deleted or edited. Clone the template first.", 'zh-CN': "内置模板不能删除或修改，请先克隆。"},
  COUNTRY_TEMPLATE_IN_USE: {en: "This country template is still used by a committee template. Change that reference first.", 'zh-CN': "该国家模板仍被委员会模板使用，请先更换关联模板。"},
  ADMIN_CANNOT_CREATE_COMMITTEE: {en: "System administrators cannot create committees. Use a regular account.", 'zh-CN': "系统管理员账号不能创建委员会，请使用普通账号。"},
  TEMPLATE_SELECTION_REQUIRED: {en: "Choose one committee template or one country template, not both.", 'zh-CN': "请选择一个委员会模板或一个国家模板，不能同时选择两种。"},
  INVALID_SEAT_PROPERTIES: {en: "Check the seat type and voting rights. Veto power and required voting need voting rights enabled.", 'zh-CN': "请检查席位类别和表决权；否决权或不得弃权要求先启用表决权。"},
  SEAT_PATCH_EMPTY: {en: "Select a seat setting to change.", 'zh-CN': "请选择需要修改的席位设置。"},
  OWN_TEXT_POST_ONLY: {en: "You can only edit or delete your own text posts.", 'zh-CN': "只能修改或删除自己发布的文本。"},
  INVALID_RULE_PHASES: {en: "The rule package has invalid meeting phases. Ask a Chair to correct the rules.", 'zh-CN': "规则包的会议阶段配置无效，请联系主席修正规则。"},
  INVALID_GENERAL_LIST_ACTION: {en: "Choose the existing list or confirm creation of a replacement.", 'zh-CN': "请选择保留现有名单或确认创建替代名单。"},
  RULE_PHASE_UNAVAILABLE: {en: "The selected meeting phase is not defined in the current rules. Select another phase.", 'zh-CN': "当前规则未定义所选会议阶段，请重新选择。"},
  MULTIPLE_PENDING_MEETINGS: {en: "Multiple sessions are pending. Ask an administrator to check the session records.", 'zh-CN': "存在多个待开始会期，请联系管理员检查会期记录。"},
  MEETING_ALREADY_CLOSED: {en: "This meeting session is already closed. Refresh its status.", 'zh-CN': "该会期已经结束，请刷新会期状态。"},
  INVALID_ROLL_CALL_RULES: {en: "The rule package has invalid roll-call responses. Ask a Chair to correct the rules.", 'zh-CN': "规则包的点名回答配置无效，请联系主席修正规则。"},
  NO_ACTIVE_SEATS: {en: "The committee has no active seats. Add or enable seats first.", 'zh-CN': "委员会没有活动席位，请先添加或启用席位。"},
  ROLL_CALL_NOT_ACTIVE: {en: "Roll Call has not started or has ended. Refresh its status.", 'zh-CN': "当前点名尚未开始或已经结束，请刷新点名状态。"},
  ROLL_CALL_RESPONSE_REQUIRED: {en: "Record the current seat's roll-call response first.", 'zh-CN': "请先记录当前席位的点名回答。"},
  INVALID_ROLL_CALL_RESPONSE: {en: "Choose a response allowed in this Roll Call.", 'zh-CN': "请选择本次点名允许的回答。"},
  SEAT_NOT_IN_ROLL_CALL: {en: "This seat is not part of this Roll Call. Select a listed seat.", 'zh-CN': "该席位不在本次点名名单中，请选择名单内席位。"},
  ROLL_CALL_NOTHING_TO_UNDO: {en: "This Roll Call has no response to undo.", 'zh-CN': "本次点名没有可撤销的回答。"},
  INVALID_ATTENDANCE_EVENT: {en: "Select a valid attendance change, such as arrival, temporary leave, or return.", 'zh-CN': "请选择出席、暂离或返回等有效出席变更。"},
  REPRESENTED_SEAT_REQUIRED: {en: "Select the represented seat first.", 'zh-CN': "请先选择代办席位。"},
  INVALID_POINT_RULES: {en: "The rule package has invalid point types. Ask a Chair to correct the rules.", 'zh-CN': "规则包的问题类型配置无效，请联系主席修正规则。"},
  POINT_TYPE_UNAVAILABLE: {en: "This point type is not in the current session rules. Select another type.", 'zh-CN': "该问题类型不在当前会期规则中，请重新选择。"},
  INVALID_POINT_RESULT: {en: "Choose a valid ruling for this point.", 'zh-CN': "请选择有效的问题裁定结果。"},
  POINT_ALREADY_RESOLVED: {en: "This point is already resolved. Refresh the point list.", 'zh-CN': "该问题已经裁定，请刷新问题列表。"},
  POINT_NOT_WITHDRAWABLE: {en: "Only a pending point can be deleted. Refresh the point list.", 'zh-CN': "只能删除待处理的问题，请刷新问题列表。"},
  ATTENDANCE_POINT_REQUIRED: {en: "Only a personal privilege point can change attendance.", 'zh-CN': "只有个人特权问题可以同时修改出席状态。"},
  INVALID_TEXT_PATCH: {en: "The text update contains invalid fields. Reload and edit again.", 'zh-CN': "文本修改内容包含无效字段，请刷新后重新编辑。"},
  TEXT_PATCH_EMPTY: {en: "Enter a text change first.", 'zh-CN': "请先填写需要修改的文本。"},
  RESOURCE_ALREADY_EXISTS: {en: "This record already exists. Refresh the list and check for duplicates.", 'zh-CN': "该记录已经存在，请刷新列表检查重复项。"},
  COMMITTEE_PAUSED: {en: "The committee is paused. Resume it first.", 'zh-CN': "委员会已暂停，请先恢复委员会。"},
  FILE_REPLACEMENT_CONFIRMATION_REQUIRED: {en: "This name already exists. Open file review to confirm the replacement.", 'zh-CN': "该名称已存在，请在文件审核中确认替换。"},
  FILE_REPLACEMENT_CHANGED: {en: "The file changed. Refresh and confirm the replacement again.", 'zh-CN': "文件已变化，请刷新后重新确认替换。"},
  FILE_UPDATE_REQUIRES_REVIEW: {en: "Upload a new submission on the web and approve it to update this file.", 'zh-CN': "请通过网页上传新提交，并审核批准以更新此文件。"},
  DOCUMENT_FILE_NOT_PUBLISHED: {en: "This file is unavailable. Choose a published file from this committee.", 'zh-CN': "此文件不可用，请选择本委员会已发布的文件。"},
  SAVE_TIMEOUT: {en: "Saving timed out. Try again.", "zh-CN": "保存超时，请重试。"},
  IMAGE_REQUIRED: {en: "Please choose an image file", "zh-CN": "请选择图片文件"},
  FLAG_TOO_LARGE: {en: "Flag images must be smaller than 5 MB", "zh-CN": "旗帜图片必须小于 5 MB"},
  FLAG_PROCESSING_FAILED: {en: "Could not process flag image", "zh-CN": "无法处理旗帜图片"},
  CHAIR_HOST_REQUIRED: {en: "No chair computer is paired.", "zh-CN": "当前没有主席电脑。"},
  CHAIR_COMMIT_PENDING: {en: "Waiting for Chair computer to save the file", "zh-CN": "等待主席电脑保存文件"},
  THEME_TOO_LARGE: {en: "Theme file is too large. The maximum size is 3 MB.", "zh-CN": "主题文件过大，最大为 3 MB。"},

  INVALID_FILE_EXTENSION: {en: 'Allowed file formats: {formats}', 'zh-CN': '允许的文件格式：{formats}'},
  BAD_REQUEST: {en: "The request is invalid.", 'zh-CN': "请求无效。"},
  AUTHENTICATION_REQUIRED: {en: "Please log in again.", 'zh-CN': "请重新登录。"},
  FORBIDDEN: {en: "You do not have permission to perform this action.", 'zh-CN': "你没有权限执行此操作。"},
  NOT_FOUND: {en: "The requested resource was not found.", 'zh-CN': "未找到请求的内容。"},
  METHOD_NOT_ALLOWED: {en: "This action is not supported.", 'zh-CN': "不支持此操作。"},
  REVISION_CONFLICT: {en: "The state changed. Reload and try again.", 'zh-CN': "状态已更新，请重新载入后重试。"},
  IDEMPOTENCY_CONFLICT: {en: "This request key was used for different content. Retry the action.", 'zh-CN': "请求标识已用于其他内容，请重新操作。"},
  RESOURCE_CONFLICT: {en: "The operation conflicts with the latest records. Refresh and review them before retrying.", 'zh-CN': "操作与最新记录冲突，请刷新并检查记录后重试。"},
  SPEAKER_ALREADY_QUEUED: {en: "This seat is already on the speaker list and cannot be added again.", 'zh-CN': "该席位已在发言名单中，不能重复加入。"},
  STALE_STORAGE_LEASE: {en: "Storage changed. Reload and try again.", 'zh-CN': "存储已变更，请重新载入后重试。"},
  CURSOR_EXPIRED: {en: "The update history expired. Reload to reconnect.", 'zh-CN': "更新记录已过期，请重新载入以连接。"},
  LINK_EXPIRED: {en: "This link has expired.", 'zh-CN': "链接已失效。"},
  PAYLOAD_TOO_LARGE: {en: "The file is too large. Choose a smaller file.", 'zh-CN': "文件过大，请选择较小的文件。"},
  VALIDATION_FAILED: {en: "Check the entered values and try again.", 'zh-CN': "请检查输入内容后重试。"},
  CHAIR_DECISION_REQUIRED: {en: "A chair decision is required.", 'zh-CN': "需要主席裁定。"},
  RATE_LIMITED: {en: "Too many requests. Wait a while before trying again.", 'zh-CN': "请求过于频繁，请稍后重试。"},
  INTERNAL_ERROR: {en: "The server could not complete the request. Try again later.", 'zh-CN': "服务器未能完成请求，请稍后重试。"},
  SERVICE_NOT_READY: {en: "The service is unavailable. Try again later.", 'zh-CN': "服务暂不可用，请稍后重试。"},
  INVALID_COMMITTEE_LANGUAGE: {en: "Choose a supported committee language.", 'zh-CN': "请选择支持的委员会语言。"},
  MISSING_CONTENT_TRANSLATION: {en: "The selected content is missing required translations.", 'zh-CN': "所选内容缺少所需语言的翻译。"},
  SOURCE_REVISION_CHANGED: {en: "The selected source changed. Refresh the preview.", 'zh-CN': "所选来源已变更，请刷新预览。"},
  UNKNOWN_FIXED_MEMBER: {en: "Select a member from the committee directory.", 'zh-CN': "请从委员会固定目录选择成员。"},
  INVALID_EMAIL: {en: "Enter a valid email address.", 'zh-CN': "请输入有效的邮箱地址。"},
  DISPLAY_NAME_REQUIRED: {en: "Enter a display name.", 'zh-CN': "请输入显示名称。"},
  PASSWORD_TOO_SHORT: {en: "Password must be at least 12 characters.", 'zh-CN': "密码至少需要 12 个字符。"},
  BOOTSTRAP_SECRET_REQUIRED: {en: "Bootstrap secret is required.", 'zh-CN': "请输入初始化密钥。"},
  INCORRECT_CREDENTIALS: {en: "Email or password is incorrect.", 'zh-CN': "邮箱或密码不正确。"},
  INCORRECT_PASSWORD: {en: "Password is incorrect.", 'zh-CN': "密码不正确。"},
  INCORRECT_CURRENT_PASSWORD: {en: "Current password is incorrect.", 'zh-CN': "当前密码不正确。"},
  EMAIL_IN_USE: {en: "This email address is already in use.", 'zh-CN': "该邮箱地址已被使用。"},
  ACCOUNT_NOT_ACTIVE: {en: "Only active accounts support this action.", 'zh-CN': "只有活动账号可以执行此操作。"},
  ADMIN_ACCOUNT_PROTECTED: {en: "The system administrator account cannot be disabled or anonymized.", 'zh-CN': "不能停用或匿名化系统管理员账号。"},
  ACCOUNT_DISABLE_REQUIRED: {en: "Disable the account before anonymizing it.", 'zh-CN': "请先停用账号，再进行匿名化。"},
  INVALID_REPLACEMENT_ACCOUNT: {en: "Select an active replacement account.", 'zh-CN': "请选择活动的接收账号。"},
  CONFIRMATION_EMAIL_MISMATCH: {en: "The confirmation email does not match.", 'zh-CN': "确认邮箱不匹配。"},
  COMMITTEE_DELETION_PENDING: {en: "Wait for committee deletion to finish.", 'zh-CN': "请等待委员会删除完成。"},
  PASSWORD_CHANGE_REQUIRED: {en: "Change the temporary password first.", 'zh-CN': "请先修改临时密码。"},
  SYSTEM_ADMIN_REQUIRED: {en: "System administrator access is required.", 'zh-CN': "需要系统管理员权限。"},
  INVALID_FIELD: {en: "Check the highlighted field.", 'zh-CN': "请检查标记的字段。"},
  NETWORK_ERROR: {en: "Unable to connect. Check your network and try again.", 'zh-CN': "无法连接，请检查网络后重试。"},
  INVALID_RESPONSE: {en: "The server returned an invalid response. Try again later.", 'zh-CN': "服务器返回了无效响应，请稍后重试。"},
  ABORTED: {en: "The operation was cancelled.", 'zh-CN': "操作已取消。"},
  OPERATION_FAILED: {en: "Request failed. Try again later.", 'zh-CN': "请求失败，请稍后重试。"},
 } as const;
export type LocalizedErrorReason = keyof typeof ERROR_TEXT;

/** Unknown server messages and exception bodies never become user-facing text. */
export function formatApiError(error: unknown, language: ContentLanguage): string {
  const value = error && typeof error === 'object' ? error as {
    code?: unknown; requestId?: unknown; reason?: unknown; params?: {formats?: unknown; max?: unknown}; localization?: {reason?: unknown; params?: {formats?: unknown; max?: unknown}}; name?: unknown;
  } : undefined;
  const reason = value?.localization?.reason ?? value?.reason;
  const key = typeof reason === 'string' && Object.hasOwn(ERROR_TEXT, reason) ? reason
    : typeof value?.code === 'string' && Object.hasOwn(ERROR_TEXT, value.code) ? value.code
      : value?.name === 'AbortError' ? 'ABORTED' : 'OPERATION_FAILED';
  let text: string = ERROR_TEXT[key as LocalizedErrorReason][language];
  if (['OPERATION_FAILED', 'INTERNAL_ERROR', 'INVALID_RESPONSE', 'RESOURCE_CONFLICT', 'SERVICE_NOT_READY'].includes(key) && typeof value?.requestId === 'string' && /^[A-Za-z0-9_-]{1,128}$/.test(value.requestId)) {
    text += language === 'zh-CN' ? ` 请求编号：${value.requestId}` : ` Request ID: ${value.requestId}`;
  }
  const maximum = value?.localization?.params?.max ?? value?.params?.max;
  if (text.includes('{max}')) text = text.replace('{max}', typeof maximum === 'number' && Number.isSafeInteger(maximum)
    && maximum >= 0 ? String(maximum) : '—');
  const formats = value?.localization?.params?.formats ?? value?.params?.formats;
  return key === 'INVALID_FILE_EXTENSION' ? text.replace('{formats}',
    typeof formats === 'string' && formats.length <= 2048 && /^[a-zA-Z0-9., ]+$/.test(formats) ? formats : '—') : text;
}
