export const CONTRACT_VERSION = 2 as const;

export const ERROR_DEFINITIONS = [
  {code: 'BAD_REQUEST', httpStatus: 400},
  {code: 'AUTHENTICATION_REQUIRED', httpStatus: 401},
  {code: 'FORBIDDEN', httpStatus: 403},
  {code: 'NOT_FOUND', httpStatus: 404},
  {code: 'METHOD_NOT_ALLOWED', httpStatus: 405},
  {code: 'REVISION_CONFLICT', httpStatus: 409},
  {code: 'IDEMPOTENCY_CONFLICT', httpStatus: 409},
  {code: 'RESOURCE_CONFLICT', httpStatus: 409},
  {code: 'STALE_STORAGE_LEASE', httpStatus: 409},
  {code: 'CURSOR_EXPIRED', httpStatus: 410},
  {code: 'LINK_EXPIRED', httpStatus: 410},
  {code: 'PAYLOAD_TOO_LARGE', httpStatus: 413},
  {code: 'VALIDATION_FAILED', httpStatus: 422},
  {code: 'CHAIR_DECISION_REQUIRED', httpStatus: 422},
  {code: 'RATE_LIMITED', httpStatus: 429},
  {code: 'INTERNAL_ERROR', httpStatus: 500},
  {code: 'SERVICE_NOT_READY', httpStatus: 503}
] as const;

export type ApiErrorCode = typeof ERROR_DEFINITIONS[number]['code'];

export const ERROR_HTTP_STATUS: Readonly<Record<ApiErrorCode, number>> = Object.freeze(
  Object.fromEntries(ERROR_DEFINITIONS.map(({code, httpStatus}) => [code, httpStatus])) as Record<ApiErrorCode, number>
);

export const COMMITTEE_EVENT_DEFINITIONS = [
  {name: 'sync.cursor_advanced', defaultAudience: 'PUBLIC'},
  {name: 'committee.created', defaultAudience: 'MEMBER'},
  {name: 'committee.updated', defaultAudience: 'MEMBER'},
  {name: 'committee.chair_granted', defaultAudience: 'MEMBER'},
  {name: 'committee.chair_revoked', defaultAudience: 'MEMBER'},
  {name: 'operation_mode.changed', defaultAudience: 'MEMBER'},
  {name: 'committee.status_changed', defaultAudience: 'MEMBER'},
  {name: 'seat.created', defaultAudience: 'MEMBER'},
  {name: 'seat.updated', defaultAudience: 'MEMBER'},
  {name: 'seat.deactivated', defaultAudience: 'MEMBER'},
  {name: 'seat.assignment_started', defaultAudience: 'MEMBER'},
  {name: 'seat.assignment_ended', defaultAudience: 'MEMBER'},
  {name: 'seat.invitation_created', defaultAudience: 'CHAIR'},
  {name: 'seat.invitation_revoked', defaultAudience: 'CHAIR'},
  {name: 'seat.invitation_redeemed', defaultAudience: 'MEMBER'},
  {name: 'attendance.changed', defaultAudience: 'MEMBER'},
  {name: 'meeting_session.started', defaultAudience: 'MEMBER'},
  {name: 'meeting_session.closed', defaultAudience: 'MEMBER'},
  {name: 'roll_call.started', defaultAudience: 'MEMBER'},
  {name: 'roll_call.response_recorded', defaultAudience: 'MEMBER'},
  {name: 'roll_call.response_undone', defaultAudience: 'MEMBER'},
  {name: 'roll_call.reset', defaultAudience: 'MEMBER'},
  {name: 'roll_call.completed', defaultAudience: 'MEMBER'},
  {name: 'point.raised', defaultAudience: 'MEMBER'},
  {name: 'point.resolved', defaultAudience: 'MEMBER'},
  {name: 'note.created', defaultAudience: 'MEMBER'},
  {name: 'note.updated', defaultAudience: 'MEMBER'},
  {name: 'note.deleted', defaultAudience: 'MEMBER'},
  {name: 'text_post.created', defaultAudience: 'MEMBER'},
  {name: 'text_post.updated', defaultAudience: 'MEMBER'},
  {name: 'text_post.deleted', defaultAudience: 'MEMBER'},
  {name: 'speaker_request.created', defaultAudience: 'CHAIR'},
  {name: 'speaker_list.created', defaultAudience: 'MEMBER'},
  {name: 'speaker_queue.changed', defaultAudience: 'MEMBER'},
  {name: 'speech.changed', defaultAudience: 'MEMBER'},
  {name: 'speech.yielded', defaultAudience: 'MEMBER'},
  {name: 'speech.contribution_recorded', defaultAudience: 'MEMBER'},
  {name: 'caucus.closed', defaultAudience: 'MEMBER'},
  {name: 'timer.changed', defaultAudience: 'MEMBER'},
  {name: 'timer.expired', defaultAudience: 'MEMBER'},
  {name: 'motion.proposed', defaultAudience: 'MEMBER'},
  {name: 'motion.seconded', defaultAudience: 'MEMBER'},
  {name: 'motion.decided', defaultAudience: 'MEMBER'},
  {name: 'ballot.opened', defaultAudience: 'MEMBER'},
  {name: 'ballot.vote_recorded', defaultAudience: 'CHAIR'},
  {name: 'ballot.vote_corrected', defaultAudience: 'CHAIR'},
  {name: 'ballot.result_published', defaultAudience: 'PUBLIC'},
  {name: 'strawpoll.created', defaultAudience: 'PUBLIC'},
  {name: 'strawpoll.vote_recorded', defaultAudience: 'PUBLIC'},
  {name: 'strawpoll.closed', defaultAudience: 'PUBLIC'},
  {name: 'document.created', defaultAudience: 'MEMBER'},
  {name: 'document.version_created', defaultAudience: 'MEMBER'},
  {name: 'document.status_changed', defaultAudience: 'PUBLIC'},
  {name: 'document.discussion_added', defaultAudience: 'MEMBER'},
  {name: 'file.created', defaultAudience: 'MEMBER'},
  {name: 'file.sync_state_changed', defaultAudience: 'MEMBER'},
  {name: 'file.deleted', defaultAudience: 'MEMBER'},
  {name: 'storage_host.status_changed', defaultAudience: 'CHAIR'},
  {name: 'rule_package.activated', defaultAudience: 'MEMBER'},
  {name: 'rule_package.version_created', defaultAudience: 'CHAIR'},
  {name: 'rule_override.created', defaultAudience: 'CHAIR'},
  {name: 'committee.archived', defaultAudience: 'MEMBER'},
  {name: 'committee.deletion_started', defaultAudience: 'MEMBER'}
] as const;

export type EventAudience = 'PUBLIC' | 'MEMBER' | 'CHAIR';
export type CommitteeEventName = typeof COMMITTEE_EVENT_DEFINITIONS[number]['name'];

export const AUDIT_ACTION_DEFINITIONS = [
  'system.bootstrap_admin_created',
  'identity.login_succeeded',
  'identity.login_failed',
  'identity.session_elevated',
  'identity.session_revoked',
  'identity.password_changed',
  'admin.user_created',
  'admin.user_password_reset',
  'admin.user_disabled',
  'admin.user_anonymized',
  'committee.created',
  'committee.updated',
  'committee.operation_mode_changed',
  'committee.status_changed',
  'committee.chair_granted',
  'committee.chair_revoked',
  'committee.archived',
  'committee.deleted',
  'committee.deletion_started',
  'committee.seat_created',
  'committee.seat_updated',
  'committee.seat_deactivated',
  'committee.seat_assigned',
  'committee.seat_assignment_ended',
  'committee.seat_invitation_created',
  'committee.seat_invitation_revoked',
  'committee.seat_invitation_redeemed',
  'templates.country_created',
  'templates.country_updated',
  'templates.country_cloned',
  'templates.country_deleted',
  'templates.committee_created',
  'templates.committee_updated',
  'templates.committee_cloned',
  'templates.committee_deleted',
  'proceedings.note_created',
  'proceedings.note_updated',
  'proceedings.note_deleted',
  'proceedings.text_post_created',
  'proceedings.text_post_updated',
  'proceedings.text_post_deleted',
  'proceedings.meeting_session_started',
  'proceedings.meeting_session_closed',
  'proceedings.roll_call_started',
  'proceedings.roll_call_response_recorded',
  'proceedings.roll_call_response_undone',
  'proceedings.roll_call_reset',
  'proceedings.roll_call_completed',
  'proceedings.attendance_changed',
  'proceedings.point_raised',
  'proceedings.point_resolved',
  'proceedings.chair_acted_on_behalf',
  'timers.created',
  'timers.started',
  'timers.paused',
  'timers.resumed',
  'timers.extended',
  'timers.reset',
  'timers.expired',
  'proceedings.speaker_list_created',
  'proceedings.speaker_joined_queue',
  'proceedings.speaker_queue_reordered',
  'proceedings.speaker_advanced',
  'proceedings.caucus_closed',
  'proceedings.speech_started',
  'proceedings.speech_paused',
  'proceedings.speech_resumed',
  'proceedings.speech_completed',
  'proceedings.speech_yielded',
  'proceedings.speech_contribution_recorded',
  'proceedings.motion_proposed',
  'proceedings.motion_seconded',
  'proceedings.motion_decided',
  'voting.ballot_created',
  'voting.ballot_opened',
  'voting.vote_cast',
  'voting.vote_corrected',
  'voting.ballot_closed',
  'voting.result_published',
  'voting.strawpoll_created',
  'voting.strawpoll_vote_recorded',
  'voting.strawpoll_closed',
  'documents.created',
  'documents.version_created',
  'documents.status_changed',
  'documents.discussion_added',
  'storage.file_version_recorded',
  'rules.package_activated',
  'rules.package_imported',
  'rules.package_cloned',
  'rules.version_created',
  'rules.chair_override_applied',
  'storage.binding_changed',
  'storage.host_transferred',
  'storage.file_deleted'
] as const;

export type AuditAction = typeof AUDIT_ACTION_DEFINITIONS[number];
