import type {ApiErrorBody} from '@quorum/contracts';
export class AgentFileSystemError extends Error {
  constructor(readonly code: 'INVALID_STORAGE_ROOT' | 'UNSAFE_LOCAL_PATH' | 'LOCAL_CONTENT_CONFLICT'
    | 'LOCAL_CONTENT_INVALID' | 'LOCAL_WRITE_FAILED', message: string, readonly cause?: unknown) {
    super(message);
    this.name = 'AgentFileSystemError';
  }
}

export class AgentApiError extends Error {
  constructor(readonly status: number, readonly code: string, message: string, readonly details?: unknown,
    readonly localization?: Pick<ApiErrorBody['error'], 'reason' | 'params' | 'fieldErrors'>) {
    super(message);
    this.name = 'AgentApiError';
  }
}

// Kept in sync with the fixed desktop translations; no server message crosses this boundary.
const desktopApiReasons = new Set([
  'AGENT_CONTENT_ALREADY_VERIFIED',
  'AGENT_CONTENT_NOT_STAGED',
  'AGENT_TASK_ALREADY_CLAIMED',
  'AGENT_TASK_CLAIM_LOST',
  'AGENT_TASK_CONTENT_MISMATCH',
  'AGENT_TASK_CONTENT_UNEXPECTED',
  'AGENT_TASK_NOT_AVAILABLE',
  'AGENT_UPGRADE_REQUIRED',
  'CACHE_FULL',
  'CACHE_REFILL_INCOMPLETE',
  'CHAIR_HOST_ALREADY_PAIRED',
  'CHAIR_HOST_REQUIRED',
  'CHAIR_HOST_REVOKED',
  'CHAIR_OR_OWNER_REQUIRED',
  'CHAIR_PAIRING_STATE_CHANGED',
  'CHAIR_REQUIRED',
  'CHAIR_STORAGE_UNAVAILABLE',
  'CLIENT_REQUEST_INVALID',
  'COMMITTEE_PAUSED',
  'COMMITTEE_READ_ONLY',
  'DELETED_FILE_REQUIRES_NEW',
  'FILE_INTEGRITY_FAILED',
  'FILE_UPDATE_REQUIRES_REVIEW',
  'INVALID_CHECKSUM',
  'INVALID_CONFLICT_CHOICE',
  'INVALID_CONFLICT_CONTENT',
  'INVALID_DEVICE_KEY',
  'INVALID_DEVICE_LABEL',
  'INVALID_FILE_NAME',
  'INVALID_FILE_SIZE',
  'INVALID_PAIRING_PURPOSE',
  'INVALID_REFERENCE',
  'INVALID_RESPONSE',
  'INVALID_REVISION',
  'LOCAL_COPY_REQUIRED',
  'LOCAL_FILE_CONFLICT',
  'NETWORK_ERROR',
  'NON_NEGATIVE_INTEGER_REQUIRED',
  'PASSWORD_CHANGE_REQUIRED',
  'POSITIVE_INTEGER_REQUIRED',
  'PROVIDER_BLOB_ID_INVALID',
  'PROVIDER_INPUT_INVALID',
  'PROVIDER_INTEGRITY_MISMATCH',
  'PROVIDER_SIZE_MISMATCH',
  'RESOURCE_ALREADY_EXISTS',
  'REVIEW_STORAGE_FULL',
  'REVISION_CONFLICT',
  'REVOKED_HOST_CONTENT',
  'S3_DELETE_FAILED',
  'S3_INTEGRITY_MISMATCH',
  'S3_READ_FAILED',
  'S3_VERIFICATION_FAILED',
  'S3_WRITE_FAILED',
  'SERVER_VOLUME_DELETE_FAILED',
  'SERVER_VOLUME_PATH_INVALID',
  'SERVER_VOLUME_READ_FAILED',
  'SERVER_VOLUME_WRITE_FAILED',
  'STAGING_CLEANUP_FAILED',
  'STAGING_PATH_INVALID',
  'STAGING_WRITE_FAILED',
  'STORAGE_AGENT_OFFLINE',
  'STORAGE_AGENT_SOURCE_MISSING',
  'STORAGE_AGENT_UPGRADE_REQUIRED',
  'STORAGE_CACHE_CAPACITY_UNAVAILABLE',
  'STORAGE_CAPACITY_LOW',
  'STORAGE_CAPACITY_UNAVAILABLE',
  'STORAGE_RESERVE_REQUIRED',
  'UNSAFE_FILE_NAME',
  'UPLOAD_ACCOUNT_INACTIVE',
  'UPLOAD_CREATOR_REQUIRED',
  'UPLOAD_HASH_MISMATCH',
  'UPLOAD_INTERRUPTED',
  'UPLOAD_NOT_READY',
  'UPLOAD_SIZE_MISMATCH',
  'UPLOAD_STATE_CHANGED',
  'UPLOAD_TOO_LARGE',
]);

// Only fixed codes cross the desktop boundary; never forward exception messages or server bodies.
export function agentErrorCode(error: unknown, depth = 0): string {
  if (depth > 4) return 'OPERATION_FAILED';
  if (error instanceof AgentApiError && error.localization?.reason && desktopApiReasons.has(error.localization.reason)) {
    return error.localization.reason;
  }
  const value = error as {code?: string; message?: string; cause?: unknown} | undefined;
  const codes = ['AGENT_ALREADY_RUNNING','UNSAFE_AGENT_LOCK','CONFIG_EXISTS','ROOT_ALREADY_PAIRED',
    'CONFIG_PATH_REQUIRED','CONFIG_REQUIRED','STOP_FIRST','ROOT_IDENTITY_MISMATCH','MOVE_COMPLETE_DIRECTORY',
    'SERVER_CERTIFICATE_CHANGED','INVALID_DRAFT','REVOKE_FAILED','CONFIG_PATH_CHANGED','CONFIG_OUTSIDE_ROOT',
    'INVALID_SCAN_INTERVAL','INVALID_CERTIFICATE','PAIRING_FAILED','UNSAFE_PATH','HTTPS_REQUIRED',
    'PAIRING_CODE_REQUIRED','DEVICE_LABEL_REQUIRED','ROOT_REQUIRED','CONFIG_INVALID','CONFIG_PRIVATE_REQUIRED',
    'UNSAVED_CHANGES','LINK_EXPIRED','RESOURCE_CONFLICT','VALIDATION_FAILED','FORBIDDEN','NOT_FOUND',
    'AUTHENTICATION_REQUIRED','STALE_STORAGE_LEASE','SERVICE_NOT_READY','RATE_LIMITED',
    'EEXIST','ENOENT','EACCES','EPERM','ENOSPC','EROFS','ENOTDIR','EISDIR','ECONNREFUSED','ENOTFOUND',
    'ETIMEDOUT','ECONNRESET','EHOSTUNREACH','ENETUNREACH','EAI_AGAIN','TLS_TIMEOUT','UND_ERR_CONNECT_TIMEOUT',
    'UNABLE_TO_GET_ISSUER_CERT_LOCALLY','UNABLE_TO_VERIFY_LEAF_SIGNATURE','UNABLE_TO_GET_ISSUER_CERT',
    'DEPTH_ZERO_SELF_SIGNED_CERT','SELF_SIGNED_CERT_IN_CHAIN','CERT_HAS_EXPIRED','CERT_NOT_YET_VALID',
    'ERR_TLS_CERT_ALTNAME_INVALID','INVALID_STORAGE_ROOT','UNSAFE_LOCAL_PATH','LOCAL_CONTENT_CONFLICT',
    'LOCAL_CONTENT_INVALID','LOCAL_WRITE_FAILED','HTTP_ERROR','NETWORK_ERROR','INVALID_RESPONSE','INCOMPLETE_RESPONSE'];
  if (value?.cause) {
    const cause = agentErrorCode(value.cause, depth + 1);
    if (cause !== 'OPERATION_FAILED') return cause;
  }
  if (codes.includes(value?.code ?? '')) return value!.code!;
  if (codes.includes(value?.message ?? '')) return value!.message!;
  if (error instanceof SyntaxError) return 'CONFIG_INVALID';
  return 'OPERATION_FAILED';
}
