use std::path::PathBuf;

pub fn translate(key: &str, language: &str) -> &'static str {
    let (en, zh) = match key {
        "" => ("", ""),
        "  ·  Last connected " => ("  ·  Last connected ", "  ·  最近连接 "),
        " · Unsaved" => (" · Unsaved", " · 未保存"),
        "A component of the path is not a directory." => ("A component of the path is not a directory.", "路径中有一项不是目录。"),
        "AGENT_ALREADY_RUNNING" => ("An Agent is already running in this directory. Stop it first.", "此目录已有 Agent 运行，请先停止原进程。"),
        "AGENT_EXITED" => ("The Agent exited unexpectedly. Check the logs.", "Agent 异常退出，请查看日志。"),
        "AUTHENTICATION_REQUIRED" => ("Device authorization is unavailable. Check pairing on the committee page.", "设备授权不可用，请在委员会网页核对配对状态。"),
        "An Agent is already running in this directory. Stop it first." => ("An Agent is already running in this directory. Stop it first.", "此目录已有 Agent 运行，请先停止原进程。"),
        "Authorization could not be revoked. Check the original server connection and version." => ("Authorization could not be revoked. Check the original server connection and version.", "撤销授权失败。请检查原服务器连接，并确认服务器已更新。"),
        "Authorization revoked" => ("Authorization revoked", "授权已撤销"),
        "BRIDGE_EXITED" => ("The Agent control process exited. Reopen the window.", "Agent 控制进程已退出，请重新打开窗口。"),
        "Back to files" => ("Back to files", "返回文件"),
        "CA certificate" => ("CA certificate", "CA 证书"),
        "CACHE_MISSING" => ("No server cache", "服务器无缓存"),
        "CACHE_MISSING_LOCAL_READY" => ("No cache - available locally", "服务器无缓存 · 本地可用"),
        "CACHE_READY" => ("Server cache available", "服务器缓存可用"),
        "CERT_HAS_EXPIRED" => ("The server certificate has expired.", "服务器证书已过期。"),
        "CERT_NOT_YET_VALID" => ("The server certificate is not valid yet. Check the computer clock.", "服务器证书尚未生效，请核对电脑时间。"),
        "CONFIG_EXISTS" => ("The configuration file exists. Import it or choose a new path.", "配置文件已存在，请导入，或指定新的配置文件路径。"),
        "CONFIG_INVALID" => ("This is not a valid Agent configuration. Check the file format.", "配置不是有效的 Agent 配置文件，请检查文件格式。"),
        "CONFIG_OUTSIDE_ROOT" => ("The private configuration and certificate must be outside the storage directory.", "私有配置和证书必须位于存储目录之外。"),
        "CONFIG_PATH_CHANGED" => ("Save writes to the original configuration. Use Save as for a new file.", "保存设置只能写回原配置；保存新文件请使用另存为。"),
        "CONFIG_PATH_REQUIRED" => ("Enter a configuration path or choose an existing configuration.", "请填写配置文件路径，或选择已有配置。"),
        "CONFIG_PRIVATE_REQUIRED" => ("The configuration must be a regular private file readable and writable only by the current user. Links are not allowed.", "配置必须为普通私有文件，仅允许当前用户读写，不能使用链接。"),
        "CONFIG_REQUIRED" => ("Import a configuration or pair the device first.", "请先导入配置或配对。"),
        "CONFLICT" => ("Conflict", "存在冲突"),
        "Cache status updated at " => ("Cache status updated at ", "缓存状态更新于 "),
        "Cancel" => ("Cancel", "取消"),
        "Cannot export logs. Check directory permissions and free space." => ("Cannot export logs. Check directory permissions and free space.", "导出日志：无法写入目标文件，请检查目录权限和磁盘空间。"),
        "Choose a storage directory." => ("Choose a storage directory.", "请选择存储目录。"),
        "Choose certificate" => ("Choose certificate", "选择证书"),
        "Choose configuration" => ("Choose configuration", "选择配置"),
        "Choose directory" => ("Choose directory", "选择目录"),
        "Close" => ("Close", "关闭"),
        "Committee web page" => ("Committee web page", "委员会网页"),
        "Configuration imported" => ("Configuration imported", "配置已导入"),
        "Configuration saved" => ("Configuration saved", "配置已保存"),
        "Connection and storage" => ("Connection and storage", "连接与存储"),
        "Copy" => ("Copy", "复制"),
        "DELETED" => ("Deleted", "已删除"),
        "DEPTH_ZERO_SELF_SIGNED_CERT" => ("The server certificate is not trusted. Select its CA certificate.", "服务器证书不受信任，请选择对应 CA 证书。"),
        "DEVICE_LABEL_REQUIRED" => ("Enter a device name.", "请输入设备名称。"),
        "DISCONNECTED" => ("Connection error", "连接异常"),
        "DOWNLOADING" => ("Downloading", "下载中"),
        "Desktop 0.1.0 · Slint 1.17.1 · Agent protocol 2" => ("Desktop 0.1.0 · Slint 1.17.1 · Agent protocol 2", "桌面外壳 0.1.0 · Slint 1.17.1 · Agent 协议 2"),
        "Device authorization is unavailable. Check pairing on the committee page." => ("Device authorization is unavailable. Check pairing on the committee page.", "设备授权不可用，请在委员会网页核对配对状态。"),
        "Device name" => ("Device name", "设备名称"),
        "Discard and continue" => ("Discard and continue", "放弃修改并继续"),
        "Discard unsaved changes and continue?" => ("Discard unsaved changes and continue?", "当前输入尚未保存，放弃后继续？"),
        "EACCES" => ("Permission to access the file or directory was denied.", "没有访问文件或目录的权限。"),
        "EAI_AGAIN" => ("The network or name service is unavailable. Check your connection and retry.", "网络或域名解析暂不可用，请检查连接后重试。"),
        "ECONNREFUSED" => ("The server refused the connection. Check its address and whether it is running.", "服务器拒绝连接，请检查地址和服务是否启动。"),
        "ECONNRESET" => ("The server closed the connection. Try again.", "服务器中断连接，请重试。"),
        "EEXIST" => ("The target file exists. Choose another file name.", "目标文件已存在，请选择新的文件名。"),
        "EHOSTUNREACH" => ("The network or name service is unavailable. Check your connection and retry.", "网络或域名解析暂不可用，请检查连接后重试。"),
        "EISDIR" => ("The selected path is a directory. Choose a file.", "所选路径是目录，请选择文件。"),
        "ENETUNREACH" => ("The network or name service is unavailable. Check your connection and retry.", "网络或域名解析暂不可用，请检查连接后重试。"),
        "ENOENT" => ("The file or directory does not exist.", "文件或目录不存在。"),
        "ENOSPC" => ("The disk is full.", "磁盘空间不足。"),
        "ENOTDIR" => ("A component of the path is not a directory.", "路径中有一项不是目录。"),
        "ENOTFOUND" => ("The server address could not be resolved.", "无法解析服务器地址。"),
        "EPERM" => ("The system denied access. Check file permissions.", "系统拒绝访问，请检查文件权限。"),
        "EROFS" => ("The target filesystem is read-only.", "目标位于只读文件系统。"),
        "ERR_TLS_CERT_ALTNAME_INVALID" => ("The server address does not match the certificate name.", "服务器地址与证书名称不匹配。"),
        "ETIMEDOUT" => ("The server connection timed out.", "服务器连接超时。"),
        "EXITED" => ("Exited", "已退出"),
        "Enter a configuration path or choose an existing configuration." => ("Enter a configuration path or choose an existing configuration.", "请填写配置文件路径，或选择已有配置。"),
        "Enter a device name." => ("Enter a device name.", "请输入设备名称。"),
        "Enter an HTTPS server address without a path, query or credentials." => ("Enter an HTTPS server address without a path, query or credentials.", "请输入不含路径、查询或凭据的 HTTPS 服务器地址。"),
        "Enter the one-time pairing code." => ("Enter the one-time pairing code.", "请输入一次性配对码。"),
        "Export" => ("Export", "导出"),
        "FAILED" => ("Failed", "失败"),
        "FORBIDDEN" => ("Device authorization is unavailable. Check pairing on the committee page.", "设备授权不可用，请在委员会网页核对配对状态。"),
        "Files" => ("Files", "文件"),
        "Filter logs" => ("Filter logs", "筛选日志"),
        "Full scan interval (seconds)" => ("Full scan interval (seconds)", "完整扫描间隔（秒）"),
        "HTTPS_REQUIRED" => ("Enter an HTTPS server address without a path, query or credentials.", "请输入不含路径、查询或凭据的 HTTPS 服务器地址。"),
        "HTTP_ERROR" => ("The expected server interface is unavailable. Check the server address and version.", "服务器未提供预期接口，请检查服务地址及服务器版本。"),
        "Hide logs" => ("Hide logs", "收起日志"),
        "INVALID_CERTIFICATE" => ("The certificate file is invalid.", "证书文件无效。"),
        "INVALID_DRAFT" => ("The unpaired configuration is invalid.", "未配对配置格式无效。"),
        "INVALID_SCAN_INTERVAL" => ("The scan interval must be an integer from 1 to 3600 seconds.", "扫描间隔须为 1–3600 秒的整数。"),
        "INVALID_STORAGE_ROOT" => ("The configuration must be a regular private file readable and writable only by the current user. Links are not allowed.", "配置必须为普通私有文件，仅允许当前用户读写，不能使用链接。"),
        "Import" => ("Import", "导入"),
        "Import a configuration or pair the device first." => ("Import a configuration or pair the device first.", "请先导入配置或配对。"),
        "LANGUAGE_SAVE_FAILED" => ("Could not save the language preference.", "无法保存语言偏好。"),
        "LINK_EXPIRED" => ("The pairing code is invalid or expired. Generate another on the committee page.", "配对码无效或已过期，请在委员会网页重新生成。"),
        "LOCAL_CHANGED" => ("Local changes pending", "本地变化待同步"),
        "LOCAL_READY_REVIEW_UNKNOWN" => ("Saved locally - review unknown", "本地已保存 · 审核状态未知"),
        "Linux Chair computer" => ("Linux Chair computer", "Linux 主席电脑"),
        "Local status" => ("Local status", "本地状态"),
        "Logs exported" => ("Logs exported", "日志已导出"),
        "MOVE_COMPLETE_DIRECTORY" => ("The directory is incomplete or its contents changed. Move the entire original directory before selecting it.", "目录不完整或文件内容已变化，请完整搬迁原目录后再选择。"),
        "NOT_FOUND" => ("The expected server interface is unavailable. Check the server address and version.", "服务器未提供预期接口，请检查服务地址及服务器版本。"),
        "No matching files" => ("No matching files", "暂无匹配文件"),
        "One-time pairing code" => ("One-time pairing code", "一次性配对码"),
        "Open directory" => ("Open directory", "打开目录"),
        "PAIRING_CODE_REQUIRED" => ("Enter the one-time pairing code.", "请输入一次性配对码。"),
        "PAIRING_FAILED" => ("Pairing failed. Check the pairing code, directory and server connection.", "配对失败，请检查配对码、目录和服务器连接。"),
        "PENDING_DELETE" => ("Pending deletion", "待删除"),
        "PENDING_DOWNLOAD" => ("Pending download", "待下载"),
        "PENDING_REFILL" => ("Awaiting refill", "等待回传"),
        "PENDING_UPLOAD" => ("Pending upload", "待上传"),
        "Pair this computer" => ("Pair this computer", "配对此电脑"),
        "Pairing" => ("Pairing", "配对"),
        "Pairing completed" => ("Pairing completed", "配对成功"),
        "Pairing details" => ("Pairing details", "配对信息"),
        "Pairing failed. Check the pairing code, directory and server connection." => ("Pairing failed. Check the pairing code, directory and server connection.", "配对失败，请检查配对码、目录和服务器连接。"),
        "Permission to access the file or directory was denied." => ("Permission to access the file or directory was denied.", "没有访问文件或目录的权限。"),
        "Private configuration" => ("Private configuration", "私有配置"),
        "Process settings" => ("Process settings", "处理设置"),
        "Quorum / Chair Storage Agent" => ("Quorum / Chair Storage Agent", "Quorum  /  主席本地 Agent"),
        "RATE_LIMITED" => ("Too many requests. Try again later.", "请求过于频繁，请稍后重试。"),
        "READY_PUBLISHED" => ("Ready - published", "已就绪 - 公开可见"),
        "READY_REJECTED" => ("Ready - rejected", "已就绪 - 已驳回"),
        "READY_REVIEW" => ("Ready - awaiting review", "已就绪 - 待审核"),
        "READY_UNSUBMITTED" => ("Ready - not submitted", "已就绪 - 未提交审核"),
        "REFILLING" => ("Refilling", "正在回传"),
        "REFILL_FAILED" => ("Refill failed", "回传失败"),
        "REFILL_VERIFYING" => ("Verifying refill", "回传校验中"),
        "RESOURCE_CONFLICT" => ("The device state changed. Refresh the committee page and generate another pairing code.", "服务器上的设备状态已变化，请刷新委员会网页并重新生成配对码。"),
        "RETRYING" => ("Awaiting retry", "等待重试"),
        "REVOKE_FAILED" => ("Authorization could not be revoked. Check the original server connection and version.", "撤销授权失败。请检查原服务器连接，并确认服务器已更新。"),
        "ROOT_ALREADY_PAIRED" => ("The storage directory is already paired. Import its configuration or choose a new directory.", "存储目录已有配对记录，请导入对应配置，或选择新的存储目录。"),
        "ROOT_IDENTITY_MISMATCH" => ("The directory belongs to another device. Choose the fully moved original directory.", "目录不属于当前设备，请选择完整搬迁的原目录。"),
        "ROOT_REQUIRED" => ("Choose a storage directory.", "请选择存储目录。"),
        "RUNNING" => ("Running", "运行中"),
        "Read configuration" => ("Read configuration", "读取配置"),
        "Restart" => ("Restart", "重启"),
        "Revoke and unpair" => ("Revoke and unpair", "撤销授权并解除配对"),
        "Revoke authorization" => ("Revoke authorization", "撤销授权"),
        "Revoke this device's authorization? This device will no longer provide access to the committee's local files." => ("Revoke this device's authorization? This device will no longer provide access to the committee's local files.", "撤销原服务器对此设备的授权？原委员会的本地文件将无法继续通过此设备访问。"),
        "SELF_SIGNED_CERT_IN_CHAIN" => ("The server certificate is not trusted. Select its CA certificate.", "服务器证书不受信任，请选择对应 CA 证书。"),
        "SERVER_CERTIFICATE_CHANGED" => ("The new address has a different certificate. Device credentials were not sent. Use the original address or pair again.", "新地址证书与原服务不一致，未发送设备凭据。请使用原地址或重新配对。"),
        "SERVICE_NOT_READY" => ("The server is not ready. Try again later.", "服务器尚未就绪，请稍后重试。"),
        "STALE_STORAGE_LEASE" => ("Device authorization is unavailable. Check pairing on the committee page.", "设备授权不可用，请在委员会网页核对配对状态。"),
        "STARTING" => ("Starting", "启动中"),
        "STOPPED" => ("Stopped", "未启动"),
        "STOPPING" => ("Stopping", "停止中"),
        "STOP_FIRST" => ("Stop the Agent first.", "请先停止 Agent。"),
        "Save as" => ("Save as", "另存为"),
        "Save local pairing" => ("Save local pairing", "写入本地配对记录"),
        "Save settings" => ("Save settings", "保存设置"),
        "Save writes to the original configuration. Use Save as for a new file." => ("Save writes to the original configuration. Use Save as for a new file.", "保存设置只能写回原配置；保存新文件请使用另存为。"),
        "Scan interval" => ("Scan interval", "扫描间隔"),
        "Search files" => ("Search files", "搜索文件"),
        "Select if the server certificate is not trusted by the system" => ("Select if the server certificate is not trusted by the system", "服务器证书未受系统信任时选择"),
        "Server address" => ("Server address", "服务器地址"),
        "Server cache" => ("Server cache", "服务器缓存"),
        "Server pairing" => ("Server pairing", "服务器配对"),
        "Settings and pairing" => ("Settings and pairing", "设置与配对"),
        "Settings changed. Save them before starting." => ("Settings changed. Save them before starting.", "设置已修改，请先保存再启动。"),
        "Settings changed. Save them first, or import the original configuration again." => ("Settings changed. Save them first, or import the original configuration again.", "设置已修改，请先保存；恢复原配置请重新导入。"),
        "Show deleted" => ("Show deleted", "显示已删除"),
        "Show logs" => ("Show logs", "查看日志"),
        "Size" => ("Size", "大小"),
        "Start" => ("Start", "启动"),
        "Start the Agent to load file status" => ("Start the Agent to load file status", "启动 Agent 后读取文件状态"),
        "Stop" => ("Stop", "停止"),
        "Stop the Agent first." => ("Stop the Agent first.", "请先停止 Agent。"),
        "Storage directory" => ("Storage directory", "存储目录"),
        "TLS_TIMEOUT" => ("The server connection timed out.", "服务器连接超时。"),
        "The Agent control process exited. Reopen the window." => ("The Agent control process exited. Reopen the window.", "Agent 控制进程已退出，请重新打开窗口。"),
        "The Agent exited unexpectedly. Check the logs." => ("The Agent exited unexpectedly. Check the logs.", "Agent 异常退出，请查看日志。"),
        "The certificate file is invalid." => ("The certificate file is invalid.", "证书文件无效。"),
        "The configuration file exists. Import it or choose a new path." => ("The configuration file exists. Import it or choose a new path.", "配置文件已存在，请导入，或指定新的配置文件路径。"),
        "The configuration must be a regular private file readable and writable only by the current user. Links are not allowed." => ("The configuration must be a regular private file readable and writable only by the current user. Links are not allowed.", "配置必须为普通私有文件，仅允许当前用户读写，不能使用链接。"),
        "The device state changed. Refresh the committee page and generate another pairing code." => ("The device state changed. Refresh the committee page and generate another pairing code.", "服务器上的设备状态已变化，请刷新委员会网页并重新生成配对码。"),
        "The directory belongs to another device. Choose the fully moved original directory." => ("The directory belongs to another device. Choose the fully moved original directory.", "目录不属于当前设备，请选择完整搬迁的原目录。"),
        "The directory is incomplete or its contents changed. Move the entire original directory before selecting it." => ("The directory is incomplete or its contents changed. Move the entire original directory before selecting it.", "目录不完整或文件内容已变化，请完整搬迁原目录后再选择。"),
        "The disk is full." => ("The disk is full.", "磁盘空间不足。"),
        "The expected server interface is unavailable. Check the server address and version." => ("The expected server interface is unavailable. Check the server address and version.", "服务器未提供预期接口，请检查服务地址及服务器版本。"),
        "The file or directory does not exist." => ("The file or directory does not exist.", "文件或目录不存在。"),
        "The network or name service is unavailable. Check your connection and retry." => ("The network or name service is unavailable. Check your connection and retry.", "网络或域名解析暂不可用，请检查连接后重试。"),
        "The new address has a different certificate. Device credentials were not sent. Use the original address or pair again." => ("The new address has a different certificate. Device credentials were not sent. Use the original address or pair again.", "新地址证书与原服务不一致，未发送设备凭据。请使用原地址或重新配对。"),
        "The pairing code is invalid or expired. Generate another on the committee page." => ("The pairing code is invalid or expired. Generate another on the committee page.", "配对码无效或已过期，请在委员会网页重新生成。"),
        "The private configuration and certificate must be outside the storage directory." => ("The private configuration and certificate must be outside the storage directory.", "私有配置和证书必须位于存储目录之外。"),
        "The scan interval must be an integer from 1 to 3600 seconds." => ("The scan interval must be an integer from 1 to 3600 seconds.", "扫描间隔须为 1–3600 秒的整数。"),
        "The selected path is a directory. Choose a file." => ("The selected path is a directory. Choose a file.", "所选路径是目录，请选择文件。"),
        "The server address could not be resolved." => ("The server address could not be resolved.", "无法解析服务器地址。"),
        "The server address does not match the certificate name." => ("The server address does not match the certificate name.", "服务器地址与证书名称不匹配。"),
        "The server certificate has expired." => ("The server certificate has expired.", "服务器证书已过期。"),
        "The server certificate is not trusted. Select its CA certificate." => ("The server certificate is not trusted. Select its CA certificate.", "服务器证书不受信任，请选择对应 CA 证书。"),
        "The server certificate is not valid yet. Check the computer clock." => ("The server certificate is not valid yet. Check the computer clock.", "服务器证书尚未生效，请核对电脑时间。"),
        "The server closed the connection. Try again." => ("The server closed the connection. Try again.", "服务器中断连接，请重试。"),
        "The server connection timed out." => ("The server connection timed out.", "服务器连接超时。"),
        "The server is not ready. Try again later." => ("The server is not ready. Try again later.", "服务器尚未就绪，请稍后重试。"),
        "The server refused the connection. Check its address and whether it is running." => ("The server refused the connection. Check its address and whether it is running.", "服务器拒绝连接，请检查地址和服务是否启动。"),
        "The server rejected the pairing details. Check the device name and pairing code." => ("The server rejected the pairing details. Check the device name and pairing code.", "服务器拒绝配对信息，请检查设备名称和配对码。"),
        "The storage directory is already paired. Import its configuration or choose a new directory." => ("The storage directory is already paired. Import its configuration or choose a new directory.", "存储目录已有配对记录，请导入对应配置，或选择新的存储目录。"),
        "The system denied access. Check file permissions." => ("The system denied access. Check file permissions.", "系统拒绝访问，请检查文件权限。"),
        "The target file exists. Choose another file name." => ("The target file exists. Choose another file name.", "目标文件已存在，请选择新的文件名。"),
        "The target filesystem is read-only." => ("The target filesystem is read-only.", "目标位于只读文件系统。"),
        "The unpaired configuration is invalid." => ("The unpaired configuration is invalid.", "未配对配置格式无效。"),
        "This is not a valid Agent configuration. Check the file format." => ("This is not a valid Agent configuration. Check the file format.", "配置不是有效的 Agent 配置文件，请检查文件格式。"),
        "This step failed. Check the operation and error code in the logs." => ("This step failed. Check the operation and error code in the logs.", "未能完成此步骤，请查看日志中的操作及错误代码。"),
        "Too many requests. Try again later." => ("Too many requests. Try again later.", "请求过于频繁，请稍后重试。"),
        "Transfer progress" => ("Transfer progress", "传输进度"),
        "UNABLE_TO_GET_ISSUER_CERT" => ("The server certificate is not trusted. Select its CA certificate.", "服务器证书不受信任，请选择对应 CA 证书。"),
        "UNABLE_TO_GET_ISSUER_CERT_LOCALLY" => ("The server certificate is not trusted. Select its CA certificate.", "服务器证书不受信任，请选择对应 CA 证书。"),
        "UNABLE_TO_VERIFY_LEAF_SIGNATURE" => ("The server certificate is not trusted. Select its CA certificate.", "服务器证书不受信任，请选择对应 CA 证书。"),
        "UNCONFIRMED" => ("Unconfirmed", "状态待确认"),
        "UND_ERR_CONNECT_TIMEOUT" => ("The server connection timed out.", "服务器连接超时。"),
        "UNKNOWN" => ("Unknown", "状态未知"),
        "UNKNOWN_ERROR" => ("This step failed. Check the operation and error code in the logs.", "未能完成此步骤，请查看日志中的操作及错误代码。"),
        "UNPAIRED" => ("Not paired", "已解除配对"),
        "UNSAVED_CHANGES" => ("Settings changed. Save them before starting.", "设置已修改，请先保存再启动。"),
        "UPLOADING" => ("Uploading", "上传中"),
        "Unpair" => ("Unpair", "解除配对"),
        "VALIDATION_FAILED" => ("The server rejected the pairing details. Check the device name and pairing code.", "服务器拒绝配对信息，请检查设备名称和配对码。"),
        "VERIFYING" => ("Verifying", "校验中"),
        "Verify server certificate" => ("Verify server certificate", "验证服务器证书"),
        "Write configuration" => ("Write configuration", "写入配置"),
        "ca-certificate" => ("CA certificate", "CA 证书"),
        "config-read" => ("Read configuration", "读取配置"),
        "config-write" => ("Write configuration", "写入配置"),
        "local-state" => ("Save local pairing", "写入本地配对记录"),
        "pairing-input" => ("Pairing details", "配对信息"),
        "revoke" => ("Revoke authorization", "撤销授权"),
        "scan-interval" => ("Scan interval", "扫描间隔"),
        "server-address" => ("Server address", "服务器地址"),
        "server-pairing" => ("Server pairing", "服务器配对"),
        "storage-directory" => ("Storage directory", "存储目录"),
        "tls" => ("Verify server certificate", "验证服务器证书"),
        "—" => ("—", "—"),
        _ => ("Unknown status", "未知状态"),
    };
    if language == "zh-CN" { zh } else { en }
}

fn preference_path() -> Option<PathBuf> {
    std::env::var_os("XDG_CONFIG_HOME").filter(|value| !value.is_empty()).map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|home| PathBuf::from(home).join(".config")))
        .map(|base| base.join("quorum-agent/desktop-language"))
}

pub fn load_language() -> &'static str {
    let saved = preference_path().and_then(|path| std::fs::read_to_string(path).ok());
    match saved.as_deref().map(str::trim) {
        Some("zh-CN") => "zh-CN", Some("en") => "en",
        _ => if std::env::var("LANG").unwrap_or_default().starts_with("zh") { "zh-CN" } else { "en" },
    }
}

pub fn save_language(language: &str) -> std::io::Result<()> {
    if !matches!(language, "en" | "zh-CN") { return Err(std::io::ErrorKind::InvalidInput.into()); }
    let path = preference_path().ok_or(std::io::ErrorKind::NotFound)?;
    std::fs::create_dir_all(path.parent().unwrap())?;
    std::fs::write(path, language)
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn localized_states_and_errors_do_not_depend_on_business_names() {
        assert_eq!(translate("PENDING_DOWNLOAD", "en"), "Pending download");
        assert_eq!(translate("PENDING_DOWNLOAD", "zh-CN"), "待下载");
        assert_eq!(translate("ENOSPC", "en"), "The disk is full.");
        assert_eq!(translate("ENOSPC", "zh-CN"), "磁盘空间不足。");
        assert_eq!(translate("/private/token", "en"), "Unknown status");
    }
}
