use std::path::PathBuf;

pub fn translate(key: &str, language: &str) -> &'static str {
    let (en, zh) = match key {
        "AGENT_CONTENT_ALREADY_VERIFIED" => ("The sync file is already verified. Refresh task status.", "同步文件已校验完成，请刷新任务状态。"),
        "AGENT_CONTENT_NOT_STAGED" => ("The sync file has not been staged. Sync it again.", "同步文件尚未保存到暂存区，请重新同步。"),
        "AGENT_TASK_ALREADY_CLAIMED" => ("The sync task is already claimed. Wait for the current sync to finish.", "同步任务已被领取，请等待当前同步完成。"),
        "AGENT_TASK_CLAIM_LOST" => ("Another connection took over the sync task. Reconnect the Chair Agent.", "同步任务已由其他连接接管，请重新连接主席 Agent。"),
        "AGENT_TASK_CONTENT_MISMATCH" => ("Sync content does not match the task. Sync the file again.", "同步内容与任务不匹配，请重新同步该文件。"),
        "AGENT_TASK_CONTENT_UNEXPECTED" => ("This sync task no longer accepts content. Refresh sync status.", "该同步任务已不再接收内容，请刷新同步状态。"),
        "AGENT_TASK_NOT_AVAILABLE" => ("The sync task is no longer pending. Refresh sync status.", "同步任务已不再等待处理，请刷新同步状态。"),
        "AGENT_UPGRADE_REQUIRED" => ("The Chair Agent capabilities are incompatible. Upgrade it and reconnect.", "主席 Agent 功能版本不兼容，请升级后重新连接。"),
        "CACHE_FULL" => ("The download cache is full. Ask an administrator to free cache space or increase its limit.", "下载缓存已满，请联系管理员清理缓存或提高缓存容量。"),
        "CACHE_REFILL_INCOMPLETE" => ("The file cache is not ready. Wait for the Chair computer to sync.", "文件缓存尚未准备完成，请等待主席电脑同步。"),
        "CHAIR_HOST_ALREADY_PAIRED" => ("A Chair computer is already paired. Use transfer to replace it.", "委员会已经配对主席电脑，请使用转移功能更换电脑。"),
        "CHAIR_HOST_REQUIRED" => ("No chair computer is paired.", "当前没有主席电脑。"),
        "CHAIR_HOST_REVOKED" => ("This Chair computer was unpaired or replaced. Pair it again.", "该主席电脑已解除配对或已被替换，请重新配对。"),
        "CHAIR_OR_OWNER_REQUIRED" => ("Chair or committee owner access is required.", "需要主席或委员会所有者权限。"),
        "CHAIR_PAIRING_STATE_CHANGED" => ("The Chair computer changed during pairing. Refresh and generate a new pairing code.", "配对期间主席电脑状态已变化，请刷新并重新生成配对码。"),
        "CHAIR_REQUIRED" => ("Chair access is required.", "需要主席权限。"),
        "CHAIR_STORAGE_UNAVAILABLE" => ("Chair computer storage is unavailable. Check its connection and pairing status.", "主席电脑存储暂不可用，请检查电脑连接和配对状态。"),
        "CLIENT_REQUEST_INVALID" => ("The request format is incompatible with the server. Reload the page or update the Chair Agent.", "请求格式与服务器不兼容，请刷新页面或更新主席 Agent。"),
        "COMMITTEE_PAUSED" => ("The committee is paused. Resume it first.", "委员会已暂停，请先恢复委员会。"),
        "COMMITTEE_READ_ONLY" => ("This committee is archived or being deleted and cannot be edited.", "委员会已归档或正在删除，不能修改内容。"),
        "DELETED_FILE_REQUIRES_NEW" => ("This file was deleted. Save the content as a new file.", "该文件已删除，请将需要保留的内容另存为新文件。"),
        "FILE_INTEGRITY_FAILED" => ("File verification failed. Upload or sync the file again.", "文件校验失败，请重新上传或同步文件。"),
        "FILE_UPDATE_REQUIRES_REVIEW" => ("Upload a new submission on the web and approve it to update this file.", "请通过网页上传新提交，并审核批准以更新此文件。"),
        "INVALID_CHECKSUM" => ("File verification information is invalid. Select and upload the file again.", "文件校验信息无效，请重新选择并上传文件。"),
        "INVALID_CONFLICT_CHOICE" => ("Choose a resolution available for this conflict.", "请选择当前冲突允许的解决方式。"),
        "INVALID_CONFLICT_CONTENT" => ("The conflict resolution content is invalid. Select the file again.", "用于解决冲突的文件内容无效，请重新选择文件。"),
        "INVALID_DEVICE_KEY" => ("The device identity is invalid. Create a new pairing request.", "设备身份信息无效，请重新生成配对请求。"),
        "INVALID_DEVICE_LABEL" => ("Enter a valid device name.", "请填写有效的设备名称。"),
        "INVALID_FILE_NAME" => ("Enter a valid file name.", "请输入有效的文件名称。"),
        "INVALID_FILE_SIZE" => ("The file size is invalid. Select the file again.", "文件大小无效，请重新选择文件。"),
        "INVALID_PAIRING_PURPOSE" => ("Choose initial pairing or transfer to another Chair computer.", "请选择首次配对或转移主席电脑。"),
        "INVALID_REFERENCE" => ("The selected reference is unavailable or belongs to another resource. Refresh and select again.", "所选内容已不可用或不属于当前对象，请刷新后重新选择。"),
        "INVALID_RESPONSE" => ("The server returned an invalid response. Try again later.", "服务器返回了无效响应，请稍后重试。"),
        "INVALID_REVISION" => ("The page version is invalid. Reload and try again.", "页面版本信息无效，请刷新后重试。"),
        "LOCAL_COPY_REQUIRED" => ("Only local file content can be saved as a new file.", "只有本机文件内容可以另存为新文件。"),
        "LOCAL_FILE_CONFLICT" => ("The local file conflicts with the server. Choose how to resolve it in the file conflict list.", "本机文件与服务器记录冲突，请在文件冲突列表中选择保留方式。"),
        "NETWORK_ERROR" => ("Unable to connect. Check your network and try again.", "无法连接，请检查网络后重试。"),
        "NON_NEGATIVE_INTEGER_REQUIRED" => ("Enter a non-negative whole number.", "请输入非负整数。"),
        "PASSWORD_CHANGE_REQUIRED" => ("Change the temporary password first.", "请先修改临时密码。"),
        "POSITIVE_INTEGER_REQUIRED" => ("Enter a positive whole number.", "请输入大于零的整数。"),
        "PROVIDER_BLOB_ID_INVALID" => ("The file storage identifier is invalid. Refresh and select the file again.", "文件存储标识无效，请刷新后重新选择文件。"),
        "PROVIDER_INPUT_INVALID" => ("The file size or checksum is invalid. Select the file and upload again.", "文件大小或校验信息无效，请重新选择并上传文件。"),
        "PROVIDER_INTEGRITY_MISMATCH" => ("File verification failed. Upload or sync the file again.", "文件校验失败，请重新上传或同步。"),
        "PROVIDER_SIZE_MISMATCH" => ("The received file size does not match. Upload the file again.", "接收到的文件大小不一致，请重新上传。"),
        "RESOURCE_ALREADY_EXISTS" => ("This record already exists. Refresh the list and check for duplicates.", "该记录已经存在，请刷新列表检查重复项。"),
        "REVIEW_STORAGE_FULL" => ("Pending review storage is full. Review pending files or increase capacity first.", "待审核文件空间已满，请先处理待审核文件或增加容量。"),
        "REVISION_CONFLICT" => ("The state changed. Reload and try again.", "状态已更新，请重新载入后重试。"),
        "REVOKED_HOST_CONTENT" => ("The original Chair computer was unpaired. Upload the content again using the current computer.", "原主席电脑已解除配对，不能采用其内容，请通过当前电脑重新上传。"),
        "S3_DELETE_FAILED" => ("The S3 file could not be removed. Check the connection and bucket delete permission.", "无法清理 S3 文件，请检查连接及存储桶删除权限。"),
        "S3_INTEGRITY_MISMATCH" => ("The S3 file failed verification. Upload the file again.", "S3 文件校验失败，请重新上传。"),
        "S3_READ_FAILED" => ("The S3 file could not be read. Check the connection, credentials, and bucket read permission.", "无法读取 S3 文件，请检查连接、凭据及存储桶读取权限。"),
        "S3_VERIFICATION_FAILED" => ("The S3 read/write test failed. Check the endpoint, bucket, credentials, and permissions.", "无法读写 S3 测试文件，请检查地址、存储桶、凭据和访问权限。"),
        "S3_WRITE_FAILED" => ("S3 could not save the file. Check the connection, credentials, and bucket write permission.", "S3 无法保存文件，请检查连接、凭据及存储桶写入权限。"),
        "SERVER_VOLUME_DELETE_FAILED" => ("The server could not remove stored file content. Ask an administrator to check storage permissions.", "服务器无法清理文件内容，请联系管理员检查存储权限。"),
        "SERVER_VOLUME_PATH_INVALID" => ("The server storage directory is unsafe or unavailable. Ask an administrator to check it.", "服务器存储目录不安全或不可用，请联系管理员检查。"),
        "SERVER_VOLUME_READ_FAILED" => ("The server could not read the file. Ask an administrator to check the storage volume.", "服务器无法读取文件，请联系管理员检查存储卷。"),
        "SERVER_VOLUME_WRITE_FAILED" => ("The server could not save the file. Ask an administrator to check disk space and directory permissions.", "服务器无法保存文件，请联系管理员检查磁盘空间和目录权限。"),
        "STAGING_CLEANUP_FAILED" => ("Temporary upload files could not be removed. Ask an administrator to check directory permissions.", "无法清理临时上传文件，请联系管理员检查目录权限。"),
        "STAGING_PATH_INVALID" => ("The upload staging directory is unsafe or unavailable. Ask an administrator to check it.", "上传暂存目录不安全或不可用，请联系管理员检查。"),
        "STAGING_WRITE_FAILED" => ("The server could not stage the upload. Ask an administrator to check free disk space and directory permissions.", "服务器无法暂存上传文件，请联系管理员检查磁盘空间和目录权限。"),
        "STORAGE_AGENT_OFFLINE" => ("The Chair computer is offline. Bring it online before downloading this file.", "主席电脑已离线，请让该电脑上线后再下载此文件。"),
        "STORAGE_AGENT_SOURCE_MISSING" => ("The source file is missing or failed verification on the Chair computer. Check the file and sync again.", "主席电脑上的源文件缺失或校验失败，请检查文件并重新同步。"),
        "STORAGE_AGENT_UPGRADE_REQUIRED" => ("Update the Chair Agent to support file downloads through the server.", "请升级主席 Agent，以支持通过服务器下载文件。"),
        "STORAGE_CACHE_CAPACITY_UNAVAILABLE" => ("Download cache space is unavailable. Ask an administrator to check cache capacity and free disk space.", "下载缓存空间不可用，请联系管理员检查缓存容量和磁盘剩余空间。"),
        "STORAGE_CAPACITY_LOW" => ("Storage space is low. Free space or increase capacity before retrying.", "存储空间不足，请清理文件或扩容后重试。"),
        "STORAGE_CAPACITY_UNAVAILABLE" => ("Available storage space could not be read. Ask an administrator to check the storage volume.", "无法读取存储剩余空间，请联系管理员检查存储卷。"),
        "STORAGE_RESERVE_REQUIRED" => ("Saving this file would use reserved disk space. Free space or increase storage capacity.", "保存文件会占用服务器保留空间，请清理存储或扩容。"),
        "UNSAFE_FILE_NAME" => ("File names cannot contain absolute paths, parent-directory traversal, or reserved names.", "文件名不能包含绝对路径、上级目录跳转或系统保留名称。"),
        "UPLOAD_ACCOUNT_INACTIVE" => ("The upload account is inactive. Upload again using an active account.", "发起上传的账号已停用，请使用活动账号重新上传。"),
        "UPLOAD_CREATOR_REQUIRED" => ("Only the account that started the upload can continue it. Use that account or start a new upload.", "只有发起上传的账号可以继续该上传，请使用原账号或重新上传。"),
        "UPLOAD_HASH_MISMATCH" => ("The uploaded file failed verification. Select the file and upload again.", "上传文件校验失败，请重新选择并上传文件。"),
        "UPLOAD_INTERRUPTED" => ("The upload was interrupted. Check the connection and upload again.", "上传中断，请检查网络后重新上传。"),
        "UPLOAD_NOT_READY" => ("File content has not finished uploading or verification. Wait before retrying.", "文件内容尚未上传或校验完成，请等待后重试。"),
        "UPLOAD_SIZE_MISMATCH" => ("The uploaded file size does not match. Select the file and upload again.", "上传的文件大小不一致，请重新选择并上传文件。"),
        "UPLOAD_STATE_CHANGED" => ("This upload is completed, cancelled, or expired. Refresh its status.", "该上传已完成、已取消或已过期，请刷新上传状态。"),
        "UPLOAD_TOO_LARGE" => ("The file exceeds the upload limit. Choose a smaller file.", "文件超过上传大小限制，请选择较小的文件。"),
        "" => ("", ""),
        "  ·  Last connected " => ("  ·  Last connected ", "  ·  最近连接 "),
        " · Unsaved" => (" · Unsaved", " · 未保存"),
        "A component of the path is not a directory." => ("A component of the path is not a directory.", "路径中有一项不是目录。"),
        "AGENT_ALREADY_RUNNING" => ("An Agent is already running in this directory. Stop it first.", "此目录已有 Agent 运行，请先停止原进程。"),
        "AGENT_EXITED" => ("The Agent exited unexpectedly. Check the logs.", "Agent 异常退出，请查看日志。"),
        "AUTHENTICATION_REQUIRED" => ("Device authorization is unavailable. Check pairing on the committee page.", "设备授权不可用，请在委员会网页核对配对状态。"),
        "An Agent is already running in this directory. Stop it first." => ("An Agent is already running in this directory. Stop it first.", "此目录已有 Agent 运行，请先停止原进程。"),
        "Authorization could not be revoked. Check the original server connection and version." => ("Authorization could not be revoked. Check the original server connection and version.", "撤销授权失败。请检查原服务器连接，并确认服务器已更新。"),
        "Unpair this computer?" => ("Unpair this computer?", "解除此电脑的配对？"),
        "Unpair locally" => ("Unpair locally", "仅解除本机绑定"),
        "You can unpair locally. Server authorization has not been confirmed revoked; saved configurations may still connect." => ("You can unpair locally. Server authorization has not been confirmed revoked; saved configurations may still connect.", "可以仅解除本机绑定。服务器授权尚未确认撤销，已保存的配置仍可能连接。"),
        "Configuration and local files will be kept. Use a new storage directory to pair again." => ("Configuration and local files will be kept. Use a new storage directory to pair again.", "保留配置文件和本地文件。重新配对时需使用新的存储目录。"),
        "Unpaired locally; server authorization has not been confirmed revoked" => ("Unpaired locally; server authorization has not been confirmed revoked", "已解除本机绑定；服务器授权尚未确认撤销"),
        "Overwrite" => ("Overwrite", "覆盖"),
        "Overwrite configuration?" => ("Overwrite configuration?", "覆盖配置文件？"),
        "This file already exists. Replace its contents?" => ("This file already exists. Replace its contents?", "此文件已存在，是否覆盖其内容？"),
        "Authorization revoked" => ("Authorization revoked", "授权已撤销"),
        "BRIDGE_EXITED" => ("The Agent control process exited. Reopen the window.", "Agent 控制进程已退出，请重新打开窗口。"),
        "Back to files" => ("Back to files", "返回文件"),
        "CA certificate" => ("CA certificate", "CA 证书"),
        "CACHE_MISSING" => ("No server cache", "服务器无缓存"),
        "CACHE_MISSING_LOCAL_READY" => ("No cache - available locally", "服务器无缓存 · 本地可用"),
        "CACHE_READY" => ("Server cache available", "服务器缓存可用"),
        "CERT_HAS_EXPIRED" => ("The server certificate has expired.", "服务器证书已过期。"),
        "CERT_NOT_YET_VALID" => ("The server certificate is not valid yet. Check the computer clock.", "服务器证书尚未生效，请核对电脑时间。"),
        "CONFIG_EXISTS" => ("The configuration file exists. Import it or choose a new path.", "配置文件已存在，请导入，或指定新的配置文件路径。"),
        "CONFIG_INVALID" => ("This is not a valid Agent configuration. Check the file format.", "配置不是有效的 Agent 配置文件，请检查文件格式。"),
        "CONFIG_OUTSIDE_ROOT" => ("The private configuration and certificate must be outside the storage directory.", "私有配置和证书必须位于存储目录之外。"),
        "CONFIG_PATH_CHANGED" => ("Save writes to the original configuration. Use Save as for a new file.", "保存设置只能写回原配置；保存新文件请使用另存为。"),
        "CONFIG_PATH_REQUIRED" => ("Enter a configuration path or choose an existing configuration.", "请填写配置文件路径，或选择已有配置。"),
        "CONFIG_PRIVATE_REQUIRED" => ("The configuration must be a regular private file readable and writable only by the current user. Links are not allowed.", "配置必须为普通私有文件，仅允许当前用户读写，不能使用链接。"),
        "CONFIG_REQUIRED" => ("Import a configuration or pair the device first.", "请先导入配置或配对。"),
        "CONFLICT" => ("Conflict", "存在冲突"),
        "Cache status updated at " => ("Cache status updated at ", "缓存状态更新于 "),
        "Cancel" => ("Cancel", "取消"),
        "Cannot export logs. Check directory permissions and free space." => ("Cannot export logs. Check directory permissions and free space.", "导出日志：无法写入目标文件，请检查目录权限和磁盘空间。"),
        "Choose a storage directory." => ("Choose a storage directory.", "请选择存储目录。"),
        "Choose certificate" => ("Choose certificate", "选择证书"),
        "Choose configuration" => ("Choose configuration", "选择配置"),
        "Choose directory" => ("Choose directory", "选择目录"),
        "Close" => ("Close", "关闭"),
        "Committee web page" => ("Committee web page", "委员会网页"),
        "Configuration imported" => ("Configuration imported", "配置已导入"),
        "Configuration saved" => ("Configuration saved", "配置已保存"),
        "Connection and storage" => ("Connection and storage", "连接与存储"),
        "Copy" => ("Copy", "复制"),
        "DELETED" => ("Deleted", "已删除"),
        "DEPTH_ZERO_SELF_SIGNED_CERT" => ("The server certificate is not trusted. Select its CA certificate.", "服务器证书不受信任，请选择对应 CA 证书。"),
        "DEVICE_LABEL_REQUIRED" => ("Enter a device name.", "请输入设备名称。"),
        "DISCONNECTED" => ("Connection error", "连接异常"),
        "DOWNLOADING" => ("Downloading", "下载中"),
        "Desktop 0.1.0 · Slint 1.17.1 · Agent protocol 2" => ("Desktop 0.1.0 · Slint 1.17.1 · Agent protocol 2", "桌面外壳 0.1.0 · Slint 1.17.1 · Agent 协议 2"),
        "Device authorization is unavailable. Check pairing on the committee page." => ("Device authorization is unavailable. Check pairing on the committee page.", "设备授权不可用，请在委员会网页核对配对状态。"),
        "Device name" => ("Device name", "设备名称"),
        "Discard and continue" => ("Discard and continue", "放弃修改并继续"),
        "Discard unsaved changes and continue?" => ("Discard unsaved changes and continue?", "当前输入尚未保存，放弃后继续？"),
        "EACCES" => ("Permission to access the file or directory was denied.", "没有访问文件或目录的权限。"),
        "EAI_AGAIN" => ("The network or name service is unavailable. Check your connection and retry.", "网络或域名解析暂不可用，请检查连接后重试。"),
        "ECONNREFUSED" => ("The server refused the connection. Check its address and whether it is running.", "服务器拒绝连接，请检查地址和服务是否启动。"),
        "ECONNRESET" => ("The server closed the connection. Try again.", "服务器中断连接，请重试。"),
        "EEXIST" => ("The target file exists. Choose another file name.", "目标文件已存在，请选择新的文件名。"),
        "EHOSTUNREACH" => ("The network or name service is unavailable. Check your connection and retry.", "网络或域名解析暂不可用，请检查连接后重试。"),
        "EISDIR" => ("The selected path is a directory. Choose a file.", "所选路径是目录，请选择文件。"),
        "ENETUNREACH" => ("The network or name service is unavailable. Check your connection and retry.", "网络或域名解析暂不可用，请检查连接后重试。"),
        "ENOENT" => ("The file or directory does not exist.", "文件或目录不存在。"),
        "ENOSPC" => ("The disk is full.", "磁盘空间不足。"),
        "ENOTDIR" => ("A component of the path is not a directory.", "路径中有一项不是目录。"),
        "ENOTFOUND" => ("The server address could not be resolved.", "无法解析服务器地址。"),
        "EPERM" => ("The system denied access. Check file permissions.", "系统拒绝访问，请检查文件权限。"),
        "EROFS" => ("The target filesystem is read-only.", "目标位于只读文件系统。"),
        "ERR_TLS_CERT_ALTNAME_INVALID" => ("The server address does not match the certificate name.", "服务器地址与证书名称不匹配。"),
        "ETIMEDOUT" => ("The server connection timed out.", "服务器连接超时。"),
        "EXITED" => ("Exited", "已退出"),
        "Enter a configuration path or choose an existing configuration." => ("Enter a configuration path or choose an existing configuration.", "请填写配置文件路径，或选择已有配置。"),
        "Enter a device name." => ("Enter a device name.", "请输入设备名称。"),
        "Enter an HTTPS server address without a path, query or credentials." => ("Enter an HTTPS server address without a path, query or credentials.", "请输入不含路径、查询或凭据的 HTTPS 服务器地址。"),
        "Enter the one-time pairing code." => ("Enter the one-time pairing code.", "请输入一次性配对码。"),
        "Export" => ("Export", "导出"),
        "FAILED" => ("Failed", "失败"),
        "FORBIDDEN" => ("Device authorization is unavailable. Check pairing on the committee page.", "设备授权不可用，请在委员会网页核对配对状态。"),
        "Files" => ("Files", "文件"),
        "Filter logs" => ("Filter logs", "筛选日志"),
        "Full scan interval (seconds)" => ("Full scan interval (seconds)", "完整扫描间隔（秒）"),
        "HTTPS_REQUIRED" => ("Enter an HTTPS server address without a path, query or credentials.", "请输入不含路径、查询或凭据的 HTTPS 服务器地址。"),
        "INCOMPLETE_RESPONSE" => ("The server returned an invalid response. Try again later.", "服务器返回了无效响应，请稍后重试。"),
        "HTTP_ERROR" => ("The expected server interface is unavailable. Check the server address and version.", "服务器未提供预期接口，请检查服务地址及服务器版本。"),
        "Hide logs" => ("Hide logs", "收起日志"),
        "INVALID_CERTIFICATE" => ("The certificate file is invalid.", "证书文件无效。"),
        "INVALID_DRAFT" => ("The unpaired configuration is invalid.", "未配对配置格式无效。"),
        "INVALID_SCAN_INTERVAL" => ("The scan interval must be an integer from 1 to 3600 seconds.", "扫描间隔须为 1–3600 秒的整数。"),
        "INVALID_STORAGE_ROOT" => ("The configuration must be a regular private file readable and writable only by the current user. Links are not allowed.", "配置必须为普通私有文件，仅允许当前用户读写，不能使用链接。"),
        "Import" => ("Import", "导入"),
        "Import a configuration or pair the device first." => ("Import a configuration or pair the device first.", "请先导入配置或配对。"),
        "LANGUAGE_SAVE_FAILED" => ("Could not save the language preference.", "无法保存语言偏好。"),
        "LINK_EXPIRED" => ("The pairing code is invalid or expired. Generate another on the committee page.", "配对码无效或已过期，请在委员会网页重新生成。"),
        "LOCAL_CHANGED" => ("Local changes pending", "本地变化待同步"),
        "LOCAL_READY_REVIEW_UNKNOWN" => ("Saved locally - review unknown", "本地已保存 · 审核状态未知"),
        "Linux Chair computer" => ("Linux Chair computer", "Linux 主席电脑"),
        "Local status" => ("Local status", "本地状态"),
        "Logs exported" => ("Logs exported", "日志已导出"),
        "MOVE_COMPLETE_DIRECTORY" => ("The directory is incomplete or its contents changed. Move the entire original directory before selecting it.", "目录不完整或文件内容已变化，请完整搬迁原目录后再选择。"),
        "NOT_FOUND" => ("The expected server interface is unavailable. Check the server address and version.", "服务器未提供预期接口，请检查服务地址及服务器版本。"),
        "No matching files" => ("No matching files", "暂无匹配文件"),
        "One-time pairing code" => ("One-time pairing code", "一次性配对码"),
        "Open directory" => ("Open directory", "打开目录"),
        "PAIRING_CODE_REQUIRED" => ("Enter the one-time pairing code.", "请输入一次性配对码。"),
        "PAIRING_FAILED" => ("Pairing failed. Check the pairing code, directory and server connection.", "配对失败，请检查配对码、目录和服务器连接。"),
        "PENDING_DELETE" => ("Pending deletion", "待删除"),
        "PENDING_DOWNLOAD" => ("Pending download", "待下载"),
        "PENDING_REFILL" => ("Awaiting refill", "等待回传"),
        "PENDING_UPLOAD" => ("Pending upload", "待上传"),
        "Pair this computer" => ("Pair this computer", "配对此电脑"),
        "Pairing" => ("Pairing", "配对"),
        "Pairing completed" => ("Pairing completed", "配对成功"),
        "Pairing details" => ("Pairing details", "配对信息"),
        "Pairing failed. Check the pairing code, directory and server connection." => ("Pairing failed. Check the pairing code, directory and server connection.", "配对失败，请检查配对码、目录和服务器连接。"),
        "Permission to access the file or directory was denied." => ("Permission to access the file or directory was denied.", "没有访问文件或目录的权限。"),
        "Private configuration" => ("Private configuration", "私有配置"),
        "Process settings" => ("Process settings", "处理设置"),
        "Quorum / Chair Storage Agent" => ("Quorum / Chair Storage Agent", "Quorum  /  主席本地 Agent"),
        "RATE_LIMITED" => ("Too many requests. Try again later.", "请求过于频繁，请稍后重试。"),
        "READY_PUBLISHED" => ("Ready - published", "已就绪 - 公开可见"),
        "READY_REJECTED" => ("Ready - rejected", "已就绪 - 已驳回"),
        "READY_REVIEW" => ("Ready - awaiting review", "已就绪 - 待审核"),
        "READY_UNSUBMITTED" => ("Ready - not submitted", "已就绪 - 未提交审核"),
        "REFILLING" => ("Refilling", "正在回传"),
        "REFILL_FAILED" => ("Refill failed", "回传失败"),
        "REFILL_VERIFYING" => ("Verifying refill", "回传校验中"),
        "RESOURCE_CONFLICT" => ("The operation conflicts with the latest records. Refresh and review them before retrying.", "操作与最新记录冲突，请刷新并检查记录后重试。"),
        "RETRYING" => ("Awaiting retry", "等待重试"),
        "REVOKE_FAILED" => ("Authorization could not be revoked. Check the original server connection and version.", "撤销授权失败。请检查原服务器连接，并确认服务器已更新。"),
        "ROOT_ALREADY_PAIRED" => ("The storage directory is already paired. Import its configuration or choose a new directory.", "存储目录已有配对记录，请导入对应配置，或选择新的存储目录。"),
        "ROOT_IDENTITY_MISMATCH" => ("The directory belongs to another device. Choose the fully moved original directory.", "目录不属于当前设备，请选择完整搬迁的原目录。"),
        "ROOT_REQUIRED" => ("Choose a storage directory.", "请选择存储目录。"),
        "RUNNING" => ("Running", "运行中"),
        "Read configuration" => ("Read configuration", "读取配置"),
        "Restart" => ("Restart", "重启"),
        "Revoke and unpair" => ("Revoke and unpair", "撤销授权并解除配对"),
        "Revoke authorization" => ("Revoke authorization", "撤销授权"),
        "Revoke this device's authorization? This device will no longer provide access to the committee's local files." => ("Revoke this device's authorization? This device will no longer provide access to the committee's local files.", "撤销原服务器对此设备的授权？原委员会的本地文件将无法继续通过此设备访问。"),
        "SELF_SIGNED_CERT_IN_CHAIN" => ("The server certificate is not trusted. Select its CA certificate.", "服务器证书不受信任，请选择对应 CA 证书。"),
        "SERVER_CERTIFICATE_CHANGED" => ("The new address has a different certificate. Device credentials were not sent. Use the original address or pair again.", "新地址证书与原服务不一致，未发送设备凭据。请使用原地址或重新配对。"),
        "SERVICE_NOT_READY" => ("The server is not ready. Try again later.", "服务器尚未就绪，请稍后重试。"),
        "STALE_STORAGE_LEASE" => ("Device authorization is unavailable. Check pairing on the committee page.", "设备授权不可用，请在委员会网页核对配对状态。"),
        "STARTING" => ("Starting", "启动中"),
        "STOPPED" => ("Stopped", "未启动"),
        "STOPPING" => ("Stopping", "停止中"),
        "STOP_FIRST" => ("Stop the Agent first.", "请先停止 Agent。"),
        "Save as" => ("Save as", "另存为"),
        "Save local pairing" => ("Save local pairing", "写入本地配对记录"),
        "Save settings" => ("Save settings", "保存设置"),
        "Save writes to the original configuration. Use Save as for a new file." => ("Save writes to the original configuration. Use Save as for a new file.", "保存设置只能写回原配置；保存新文件请使用另存为。"),
        "Scan interval" => ("Scan interval", "扫描间隔"),
        "Search files" => ("Search files", "搜索文件"),
        "Select if the server certificate is not trusted by the system" => ("Select if the server certificate is not trusted by the system", "服务器证书未受系统信任时选择"),
        "Server address" => ("Server address", "服务器地址"),
        "Server cache" => ("Server cache", "服务器缓存"),
        "Server pairing" => ("Server pairing", "服务器配对"),
        "Settings and pairing" => ("Settings and pairing", "设置与配对"),
        "Settings changed. Save them before starting." => ("Settings changed. Save them before starting.", "设置已修改，请先保存再启动。"),
        "Settings changed. Save them first, or import the original configuration again." => ("Settings changed. Save them first, or import the original configuration again.", "设置已修改，请先保存；恢复原配置请重新导入。"),
        "Show deleted" => ("Show deleted", "显示已删除"),
        "Show logs" => ("Show logs", "查看日志"),
        "Size" => ("Size", "大小"),
        "Start" => ("Start", "启动"),
        "Start the Agent to load file status" => ("Start the Agent to load file status", "启动 Agent 后读取文件状态"),
        "Stop" => ("Stop", "停止"),
        "Stop the Agent first." => ("Stop the Agent first.", "请先停止 Agent。"),
        "Storage directory" => ("Storage directory", "存储目录"),
        "TLS_TIMEOUT" => ("The server connection timed out.", "服务器连接超时。"),
        "The Agent control process exited. Reopen the window." => ("The Agent control process exited. Reopen the window.", "Agent 控制进程已退出，请重新打开窗口。"),
        "The Agent exited unexpectedly. Check the logs." => ("The Agent exited unexpectedly. Check the logs.", "Agent 异常退出，请查看日志。"),
        "The certificate file is invalid." => ("The certificate file is invalid.", "证书文件无效。"),
        "The configuration file exists. Import it or choose a new path." => ("The configuration file exists. Import it or choose a new path.", "配置文件已存在，请导入，或指定新的配置文件路径。"),
        "The configuration must be a regular private file readable and writable only by the current user. Links are not allowed." => ("The configuration must be a regular private file readable and writable only by the current user. Links are not allowed.", "配置必须为普通私有文件，仅允许当前用户读写，不能使用链接。"),
        "The device state changed. Refresh the committee page and generate another pairing code." => ("The device state changed. Refresh the committee page and generate another pairing code.", "服务器上的设备状态已变化，请刷新委员会网页并重新生成配对码。"),
        "The directory belongs to another device. Choose the fully moved original directory." => ("The directory belongs to another device. Choose the fully moved original directory.", "目录不属于当前设备，请选择完整搬迁的原目录。"),
        "The directory is incomplete or its contents changed. Move the entire original directory before selecting it." => ("The directory is incomplete or its contents changed. Move the entire original directory before selecting it.", "目录不完整或文件内容已变化，请完整搬迁原目录后再选择。"),
        "The disk is full." => ("The disk is full.", "磁盘空间不足。"),
        "The expected server interface is unavailable. Check the server address and version." => ("The expected server interface is unavailable. Check the server address and version.", "服务器未提供预期接口，请检查服务地址及服务器版本。"),
        "The file or directory does not exist." => ("The file or directory does not exist.", "文件或目录不存在。"),
        "The network or name service is unavailable. Check your connection and retry." => ("The network or name service is unavailable. Check your connection and retry.", "网络或域名解析暂不可用，请检查连接后重试。"),
        "The new address has a different certificate. Device credentials were not sent. Use the original address or pair again." => ("The new address has a different certificate. Device credentials were not sent. Use the original address or pair again.", "新地址证书与原服务不一致，未发送设备凭据。请使用原地址或重新配对。"),
        "The pairing code is invalid or expired. Generate another on the committee page." => ("The pairing code is invalid or expired. Generate another on the committee page.", "配对码无效或已过期，请在委员会网页重新生成。"),
        "The private configuration and certificate must be outside the storage directory." => ("The private configuration and certificate must be outside the storage directory.", "私有配置和证书必须位于存储目录之外。"),
        "The scan interval must be an integer from 1 to 3600 seconds." => ("The scan interval must be an integer from 1 to 3600 seconds.", "扫描间隔须为 1–3600 秒的整数。"),
        "The selected path is a directory. Choose a file." => ("The selected path is a directory. Choose a file.", "所选路径是目录，请选择文件。"),
        "The server address could not be resolved." => ("The server address could not be resolved.", "无法解析服务器地址。"),
        "The server address does not match the certificate name." => ("The server address does not match the certificate name.", "服务器地址与证书名称不匹配。"),
        "The server certificate has expired." => ("The server certificate has expired.", "服务器证书已过期。"),
        "The server certificate is not trusted. Select its CA certificate." => ("The server certificate is not trusted. Select its CA certificate.", "服务器证书不受信任，请选择对应 CA 证书。"),
        "The server certificate is not valid yet. Check the computer clock." => ("The server certificate is not valid yet. Check the computer clock.", "服务器证书尚未生效，请核对电脑时间。"),
        "The server closed the connection. Try again." => ("The server closed the connection. Try again.", "服务器中断连接，请重试。"),
        "The server connection timed out." => ("The server connection timed out.", "服务器连接超时。"),
        "The server is not ready. Try again later." => ("The server is not ready. Try again later.", "服务器尚未就绪，请稍后重试。"),
        "The server refused the connection. Check its address and whether it is running." => ("The server refused the connection. Check its address and whether it is running.", "服务器拒绝连接，请检查地址和服务是否启动。"),
        "The server rejected the pairing details. Check the device name and pairing code." => ("The server rejected the pairing details. Check the device name and pairing code.", "服务器拒绝配对信息，请检查设备名称和配对码。"),
        "The storage directory is already paired. Import its configuration or choose a new directory." => ("The storage directory is already paired. Import its configuration or choose a new directory.", "存储目录已有配对记录，请导入对应配置，或选择新的存储目录。"),
        "The system denied access. Check file permissions." => ("The system denied access. Check file permissions.", "系统拒绝访问，请检查文件权限。"),
        "The target file exists. Choose another file name." => ("The target file exists. Choose another file name.", "目标文件已存在，请选择新的文件名。"),
        "The target filesystem is read-only." => ("The target filesystem is read-only.", "目标位于只读文件系统。"),
        "The unpaired configuration is invalid." => ("The unpaired configuration is invalid.", "未配对配置格式无效。"),
        "This is not a valid Agent configuration. Check the file format." => ("This is not a valid Agent configuration. Check the file format.", "配置不是有效的 Agent 配置文件，请检查文件格式。"),
        "This step failed. Check the operation and error code in the logs." => ("This step failed. Check the operation and error code in the logs.", "未能完成此步骤，请查看日志中的操作及错误代码。"),
        "Too many requests. Try again later." => ("Too many requests. Try again later.", "请求过于频繁，请稍后重试。"),
        "Transfer progress" => ("Transfer progress", "传输进度"),
        "UNABLE_TO_GET_ISSUER_CERT" => ("The server certificate is not trusted. Select its CA certificate.", "服务器证书不受信任，请选择对应 CA 证书。"),
        "UNABLE_TO_GET_ISSUER_CERT_LOCALLY" => ("The server certificate is not trusted. Select its CA certificate.", "服务器证书不受信任，请选择对应 CA 证书。"),
        "UNABLE_TO_VERIFY_LEAF_SIGNATURE" => ("The server certificate is not trusted. Select its CA certificate.", "服务器证书不受信任，请选择对应 CA 证书。"),
        "UNCONFIRMED" => ("Unconfirmed", "状态待确认"),
        "UND_ERR_CONNECT_TIMEOUT" => ("The server connection timed out.", "服务器连接超时。"),
        "UNKNOWN" => ("Unknown", "状态未知"),
        "UNKNOWN_ERROR" => ("This step failed. Check the operation and error code in the logs.", "未能完成此步骤，请查看日志中的操作及错误代码。"),
        "UNPAIRED" => ("Not paired", "已解除配对"),
        "UNSAVED_CHANGES" => ("Settings changed. Save them before starting.", "设置已修改，请先保存再启动。"),
        "UPLOADING" => ("Uploading", "上传中"),
        "Unpair" => ("Unpair", "解除配对"),
        "VALIDATION_FAILED" => ("The server rejected the request parameters. Check the current operation and update the Agent if needed.", "服务器拒绝了请求参数，请检查当前操作，必要时更新 Agent。"),
        "VERIFYING" => ("Verifying", "校验中"),
        "Verify server certificate" => ("Verify server certificate", "验证服务器证书"),
        "Write configuration" => ("Write configuration", "写入配置"),
        "ca-certificate" => ("CA certificate", "CA 证书"),
        "config-read" => ("Read configuration", "读取配置"),
        "config-write" => ("Write configuration", "写入配置"),
        "local-state" => ("Save local pairing", "写入本地配对记录"),
        "pairing-input" => ("Pairing details", "配对信息"),
        "revoke" => ("Revoke authorization", "撤销授权"),
        "scan-interval" => ("Scan interval", "扫描间隔"),
        "server-address" => ("Server address", "服务器地址"),
        "server-pairing" => ("Server pairing", "服务器配对"),
        "storage-directory" => ("Storage directory", "存储目录"),
        "tls" => ("Verify server certificate", "验证服务器证书"),
        "—" => ("—", "—"),
        _ => ("Unknown status", "未知状态"),
    };
    if language == "zh-CN" { zh } else { en }
}

fn preference_path() -> Option<PathBuf> {
    std::env::var_os("XDG_CONFIG_HOME").filter(|value| !value.is_empty()).map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|home| PathBuf::from(home).join(".config")))
        .map(|base| base.join("quorum-agent/desktop-language"))
}

pub fn load_language() -> &'static str {
    let saved = preference_path().and_then(|path| std::fs::read_to_string(path).ok());
    match saved.as_deref().map(str::trim) {
        Some("zh-CN") => "zh-CN", Some("en") => "en",
        _ => if std::env::var("LANG").unwrap_or_default().starts_with("zh") { "zh-CN" } else { "en" },
    }
}

pub fn save_language(language: &str) -> std::io::Result<()> {
    if !matches!(language, "en" | "zh-CN") { return Err(std::io::ErrorKind::InvalidInput.into()); }
    let path = preference_path().ok_or(std::io::ErrorKind::NotFound)?;
    std::fs::create_dir_all(path.parent().unwrap())?;
    std::fs::write(path, language)
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn localized_states_and_errors_do_not_depend_on_business_names() {
        assert_eq!(translate("PENDING_DOWNLOAD", "en"), "Pending download");
        assert_eq!(translate("PENDING_DOWNLOAD", "zh-CN"), "待下载");
        assert_eq!(translate("ENOSPC", "en"), "The disk is full.");
        assert_eq!(translate("ENOSPC", "zh-CN"), "磁盘空间不足。");
        assert_eq!(translate("/private/token", "en"), "Unknown status");
        assert_eq!(translate("CHAIR_HOST_REVOKED", "zh-CN"), "该主席电脑已解除配对或已被替换，请重新配对。");
        assert_eq!(translate("UPLOAD_HASH_MISMATCH", "en"), "The uploaded file failed verification. Select the file and upload again.");
        assert!(!translate("RESOURCE_CONFLICT", "en").contains("pairing"));
        assert!(!translate("VALIDATION_FAILED", "en").contains("pairing"));
    }
}
